### ISSUE TITLE
Entrypoints don't work online

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#100]
Today, I was able to build/test successfully with a box that had SGE configured correctly. Later on, in the same day, I am not able to. The only conclusion that I can draw is something was broken. I am able to build successfully offline with the latest CLI ( http://devcenter.wercker.com/learn/basics/the-wercker-cli.html ). CLI version info below. Code can be found here ( https://github.com/jakirkham/splauncher ).

    wercker version 1.0.174 (Compiled at: 2015-06-24T14:02:21Z, Git commit: ac873bc1c5a8780889fd1454940a0037aec03e2b)

**Comment by hatchan** [comment]
Could you enable support for the project, and send the id for the application?

**Comment by jakirkham** [comment]
@hatchan, yep, done.

**Comment by jakirkham** [comment]
It uses an entrypoint so maybe the entrypoint wasn't run?

**Comment by jakirkham** [comment]
Same problem can be seen on this one ( https://github.com/jakirkham/nanshe ).

**Comment by hatchan** [comment]
Yeah that's probably it. We changed the entrypoint behaviour. For main boxes you need to supply the entrypoint, using the `entrypoint` property for the box

**Comment by jakirkham** [comment]
I don't follow. I don't have access to the entrypoint script at this stage its already in the container.

**Comment by hatchan** [comment]
https://gist.github.com/hatchan/eaf9174eaff7e0363abe

**Comment by jakirkham** [comment]
Thanks for that clarification.

**Comment by hatchan** [comment]
We're changing this back, so just a second

**Comment by jakirkham** [comment]
Oops, I was trying that change in another branch.

**Comment by jakirkham** [comment]
FWIW, it did work with that change.

**Comment by jakirkham** [comment]
The idea of being able to change the entrypoint does sound interesting. It would just be nice if the default entrypoint was used when it is not specified.

**Comment by hatchan** [comment]
We will now by default use the entrypoint that the container has defined. So you can remove the wercker.yml change. 

This change will keep the ability to override the entrypoint. So should you want that, it will still be possible (also works for service boxes)

**Comment by jakirkham** [comment]
Thanks. Sounds cool. Will I still need to use this form

    box: 
       id: jakirkham/centos_drmaa_conda

or can I go back to doing this

    box: jakirkham/centos_drmaa_conda

**Comment by hatchan** [comment]
you can use both, the bottom one is shortfor the other one.

**Comment by jakirkham** [comment]
Thanks @hatchan. It appears to be working again. Really appreciated your quick response.
