### ISSUE TITLE
Failed step: setup environment - Bad status code fetching tarball: https://github.com/wercker/wercker-init/archive/v1.0.0.tar.gz

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#104]
Saw the following error in a build from yesterday.

**Comment by hatchan** [comment]
Was this just once, or does it happen each time? Also is this local or hosted wercker?

**Comment by jakirkham** [comment]
I have only seen it once thus far and it was online.

**Comment by hatchan** [comment]
Let us know if it keeps happening, closing for now

**Comment by jakirkham** [comment]
Yep, seeing this again.

**Comment by azr** [comment]
had it 4 times in a row

**Comment by ans-4175** [comment]
happened again.
what's the explanation?
