### ISSUE TITLE
internal/docker-push failed

### ISSUE THREAD

**Issue by amondnet** [wercker/support#106]
deploy:
      staging:
        - internal/docker-push:
            username: $USERNAME
            password: $PASSWORD
            tag: staging
            repository: farmers/tc-api
            registry: https://registry.hub.docker.com

PUT https://registry.hub.docker.com/v1/repositories/farmers/tc-api/ returned 400

**Comment by tal-moshayov** [comment]
same here. started yesterday. this totally kills our CI. any ETA here?

**Comment by hatchan** [comment]
We've had a issue with an dependency. Thing should be resolved now.
