### ISSUE TITLE
Ignored push to Bitbucket repo

### ISSUE THREAD

**Issue by ertrzyiks** [wercker/support#115]
I can not trigger build on any Wercker application linked to Bitbucket repo. Not sure if webhook is not sent or its actually problem on your side. I will update when once I will find out something more.

**Comment by tal-moshayov** [comment]
same here. nothing for the last 2 hours.

**Comment by tiagoovieira** [comment]
same!

**Comment by hatchan** [comment]
Thanks for reporting, we're investigating the problems right now.

**Comment by hatchan** [comment]
It looks like bitbucket is having some issues with regards to webhooks: https://bitbucket.statuspage.io/

**Comment by ertrzyiks** [comment]
@hatchan that makes sense, thanks for information. I think we can keep this ticket opened for reference until bitbucket fixes.

**Comment by hatchan** [comment]
Not sure why, but they are reporting that everything is operational again. Though I still don't see any webhooks just yet...

**Comment by pogo19** [comment]
Is there any way to execute the webhook manually? I tried to do an empty POST request to that webhook URL, got 202 Accepted but no build triggered.

**Comment by hatchan** [comment]
You can use the wercker API to trigger a build: http://devcenter.wercker.com/api/endpoints/builds.html#trigger-a-build

**Comment by jeremysuriel** [comment]
I'm seeing the same issue.  However, if i manually post to the webhook URL that is configured automatically by wercker in bitbucket, I get a 202 accepted but no build is triggered.  Not sure this is an issue on the bitbucket side...

**Comment by hatchan** [comment]
Calling the webhook URL manually won't work. This will only work when the call is coming from bitbucket. 

If you want to trigger a build, use the wercker API: http://devcenter.wercker.com/api/endpoints/builds.html#trigger-a-build

**Comment by hatchan** [comment]
It looks like webhooks are coming in again. Though there probably is a backlog, so it might take a while.

**Comment by ertrzyiks** [comment]
Yup, it works now
