### ISSUE TITLE
Generate SSK key pair usage issue

### ISSUE THREAD

**Issue by zaheershaik** [wercker/support#116]
When I generate a SSH Key Pair in wercker and try to add the key in Google Compute Instance VM Instance I get this issue `Invalid key. Required format: <protocol> <key-blob> <username@example.com>`. The problem sees self explanatory as the key doesn't end in the email format, but rather gets generated in `wercker / PROJECT_NAME / KEY_NAME` format. Please provide suggestions.

**Comment by hatchan** [comment]
You should be able to replace `wercker / PROJECT_NAME / KEY_NAME` with `<username@example.com>`.
