### ISSUE TITLE
Issues with filesystem on Docker enabled build

### ISSUE THREAD

**Issue by timflapper** [wercker/support#117]
We're seeing build steps fail because files cannot be found:

```
/pipeline/source/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load': cannot load such file -- /pipeline/source/vendor/bundle/ruby/2.1.0/specifications/bin/rake (LoadError)
	from /pipeline/source/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
```

Is there an issue with some of the machine's that are running the docker builds?

**Comment by hatchan** [comment]
Couple of questions:

- Did this just started happening?
- Does the bundle install step show any errors? 
- Could you try clearing the cache, and then rerun the build?

**Comment by timflapper** [comment]
@hatchan, it started happening today as far as I know. The bundle install step seems to work without any issues. We use our own S3 cache for bundle install, not the Wercker cache but I cleared both to be safe. We're re-running the build now.

**Comment by timflapper** [comment]
It seemed like our own cache was indeed corrupt. Sorry for the trouble. The build is working again.
