### ISSUE TITLE
You can now abort deploys when using the docker based stack! message keeps popping up again after closing

### ISSUE THREAD

**Issue by timflapper** [wercker/support#118]
Minor issue but this message keeps coming back when I refresh even after closing it:

> You can now abort deploys when using the docker based stack!

**Comment by Tonnu** [comment]
For everyone that is running into this issue, please check your browser's console to check if you're running into any `local storage` errors. If so, you can clear your local storage by running `window.localStorage.clear()`.

**Comment by timflapper** [comment]
Yep, that solved it.
