### ISSUE TITLE
Different steps for different deployments

### ISSUE THREAD

**Issue by xenoterracide** [wercker/support#122]
I would like to execute different steps depending on which branch is being deployed, is there any way to define separate deployment steps in wercker?

My real use case, I want to run `mvn deploy` on a build of master, this works fine and pushes a snapshot to my artifact server. I would like to run `mvn release...` on a build of maint, instead of mvn deploy.

I can of course find a way to tweak the maven step I've written to do this using environment variables, but I'm also thinking about more complicated situations where maybe I'm not even wanting to run the same "step", like in one deploy case where I want to deploy to an internal staging server that we can push to via ssh, or something, and then on release you have to push to s3 via its protocol.

I think something like this would work, target could either match the name given in wercker's deploy configuration, or it could have to match a set environment variable in that configuration. keytool would always be run.

~~~
deploy:
  steps:
    - xenoterracide/keytool
  target: snapshot
     steps:
       - xenoterracide/maven:
           settings: settings.xml
           goals: deploy
  target: release
     steps:
       - xenoterracide/maven:
           settings: settings.xml
           goals: release
~~~

**Comment by hatchan** [comment]
Having different deploy targets is currently already possible (though using a slightly different notation): http://devcenter.wercker.com/docs/deploy/multi-deploy-targets.html
