### ISSUE TITLE
git history suddenly truncated

### ISSUE THREAD

**Issue by eeh** [wercker/support#124]
Hello,

Suddenly, output from git log or git rev-list returns only 50, I guess by a change to git versions or something else. 

I rely on a good output from git rev-list in my wrecker scripts in order to generate a solid version number. Any ideas on how this can be achieved? 

I have tried:
 - using the --all flag to force git to fetch all history (which makes the truncated at 118)
 - backfilling the git history (using git fetch), but it seems that access to ssh keys for git is only available during the "fetch code" step

Anything you can do to help?

Kind regards,
Emil

**Comment by flenter** [comment]
Is the project using our docker enabled infrastructure?

**Comment by eeh** [comment]
Hi, 

It wasn't. But it is now. 

Still the same problem. Can't git pull from within the container, --all flag still does weird things to the log.

How are people using wercker to generate good version numbers?

Regards
Emil

**Comment by eeh** [comment]
did some progress on this issue... 

* the nodesource/node image did not include an ssh binary. switched to docker official node image instead.
* added another deployment key on bitbucket, included in build environment.

so now I can unshallow the git repo and generate a good version number. w00t!

closing.

/E

**Comment by flenter** [comment]
Very nice. I was working on a reply. Glad to see it resolved!

**Comment by eeh** [comment]
That being said, an ever-increasing build number would be useful to get from wercker, thus not having to fetch history from git :)

/E
