### ISSUE TITLE
Bundler failing with index file .idx too small error

### ISSUE THREAD

**Issue by MattReimer** [wercker/support#125]
Getting an issue with my `bundle-install` step

```
error: index file objects/pack/pack-5f8b0707cc88a19dab761925f94560fc6816987e.idx is too small
error: index file objects/pack/pack-5f8b0707cc88a19dab761925f94560fc6816987e.idx is too small
error: index file objects/pack/pack-5f8b0707cc88a19dab761925f94560fc6816987e.idx is too small
error: index file objects/pack/pack-5f8b0707cc88a19dab761925f94560fc6816987e.idx is too small
error: index file objects/pack/pack-5f8b0707cc88a19dab761925f94560fc6816987e.idx is too small
```

My wercker.yml file looks like this:
```
# our build should run within a Ruby box
box: ruby:2.1.7
build:
  steps:
    - bundle-install

    # A custom script step
    # that actually builds the jekyll site
    - script:
        name: generate site
        code: bundle exec jekyll build --trace
```

it builds just fine on my local when I run `wercker build`. This is weird. Containers should be identical no?

**Comment by causztic** [comment]
Have you tried clearing the cache? It worked for me. Bundle installing a new gem / updating a gem might be the one causing the issue with the cache.

**Comment by uzzer** [comment]
confrimed. Clearing the cache helps, while it is not fun when you have feature with one Gemfile and develop with another and you have to clear cache literally before each build.

**Comment by shinnn** [comment]
Having the same problem.

**Comment by joaodiogocosta** [comment]
+1

**Comment by DanielWright** [comment]
+1

**Comment by dynaum** [comment]
+1

**Comment by Nekromancer** [comment]
+1

**Comment by mada41** [comment]
how to clear cache:

> You can do this by going to the settings of the application and then select "Clear cache".

**Comment by asux** [comment]
Had same problem. Clear cache works! Thanks.

**Comment by alixdeschamps** [comment]
Worked for me too!

**Comment by jkubacki** [comment]
Yes, but I need to clear cache everytime there is a new gem in Gemfile. Is there any other solution?

**Comment by flbulgarelli** [comment]
Same problem here!

**Comment by uzzer** [comment]
You can disable cache by something like
```
    - script:
        name: Clear bundle cache
        code: rm -rf /pipeline/cache/bundle-install/ruby/2.2.0/cache/bundler/git/*
```

Which will increase load on Wercker and make this issue more important and urgent.

**Comment by causztic** [comment]
@uzzer I've commented on clearing the cache nearly _5 months ago_, maybe your script will tip things over the edge 📦

**Comment by jkubacki** [comment]
It is working, but it's not solution to the problem. Issues with bundler shouldn't be happening in the first place. Clearing cache on every build is kinda overkill.

**Comment by SandraKriemann** [comment]
+1

**Comment by Yanchek99** [comment]
+1 Having to clear cache with every new gem addition is frustrating.

**Comment by reelman** [comment]
+1

**Comment by ckhsponge** [comment]
+1

**Comment by hatchan** [comment]
We have released a new version of the `bundle-install` step (https://github.com/wercker/step-bundle-install#200). This new step won't fix the idx problem, but it will try to remove the `path` directory when `bundle install` fails, and then retry (up to 3 times). If you are still experiencing this problem reopen this thread.

**Comment by soudy** [comment]
Is there any progress on this? I'm on version 1.0.629 and this still happens. It removes `path` now after failing _every_ build, which is annoying with a large amount of gems.

**Comment by kntmrkm** [comment]
There is still problem.
Cleared cache does not resolve now.

```
export WERCKER_STEP_ROOT="/pipeline/bundle-install-11795afd-dc2f-442d-9b51-efc40053f2c3"
export WERCKER_STEP_ID="bundle-install-11795afd-dc2f-442d-9b51-efc40053f2c3"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="bundle-install"
export WERCKER_REPORT_NUMBERS_FILE="/report/bundle-install-11795afd-dc2f-442d-9b51-efc40053f2c3/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/bundle-install-11795afd-dc2f-442d-9b51-efc40053f2c3/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/bundle-install-11795afd-dc2f-442d-9b51-efc40053f2c3/artifacts"
export WERCKER_BUNDLE_INSTALL_CLEAR_PATH="true"
source "/pipeline/bundle-install-11795afd-dc2f-442d-9b51-efc40053f2c3/run.sh" < /dev/null
Gemfile found. Start bundle install.
bundler gem is available, and will not be installed by this step
type bundle: bundle is /usr/local/bin/bundle
bundle version: Bundler version 1.14.3
bundle install --path /pipeline/cache/bundle-install/ --retry 3
```
