### ISSUE TITLE
Request: ability to enable "auto deploy" on all branches

### ISSUE THREAD

**Issue by marshall007** [wercker/support#126]
Currently you are only allowed to enable "auto deploy" on a discrete list of branches. It would be nice if you could enable it for all successful builds across any branch.

**Comment by hatchan** [comment]
Currently there is limited support for wildcard characters (currently supported: `*`). You can use them as follows: 

- A single `*` at the beginning or at the end of the line. Match branches which have a certain prefix or suffix.
- A single `*` character. Match everything.
