### ISSUE TITLE
Request: API for displaying simple status messages on a step

### ISSUE THREAD

**Issue by marshall007** [wercker/support#127]
It would be great if there were some way for steps to return a simple status message that gets displayed in the UI. A good example use-case would be indicating the number of tests that passed or failed in a `tests` step. Here's a mockup of what I think that might look like (notice the additional text in the `tests` step):

![screen shot 2015-09-10 at 6 35 00 pm](https://cloud.githubusercontent.com/assets/877936/9803718/2114c80a-57eb-11e5-898b-362f03923fe5.png)

**Comment by hatchan** [comment]
Thanks for the feature request, and the mockup. Currently this is a already possible: 

Whatever you write to the `$WERCKER_REPORT_MESSAGE_FILE` file, will be displayed on the site.

**Comment by flenter** [comment]
Some additional info: we provide a shell function to make this easier: setMessage
See: https://github.com/wercker/wercker-init/blob/master/init.sh#L41-L43 (this script is executed in the wercker-init step)

**Comment by marshall007** [comment]
Perfect, thanks guys! By the way, this doesn't appear to be a documented feature in the new devcenter. I was only able to find a reference to `WERCKER_REPORT_MESSAGE_FILE` after searching around in the old documentation:

http://old-devcenter.wercker.com/articles/steps/guide.html

**Comment by hatchan** [comment]
Yeah we're still catching up with adding all content to the new devcenter. 

Also I recommend not using the shell function. It doesn't do anything extra, and using `$WERCKER_REPORT_MESSAGE_FILE` is available from any launguage/runtime.
