### ISSUE TITLE
/pipline/output result from "wercker build" not mounted when running "wercker deploy" via cli

### ISSUE THREAD

**Issue by ryanbauman** [wercker/support#130]
Consider the following wercker.yml.  I'm running on an Ubuntu 15.04/Docker 1.8.2 platform:

https://gist.github.com/ryanbauman/92c21c45563f386cbd56#file-wercker-yml

I expect to be able to run the following commands successfully locally via the cli, however, the deploy fails as the /pipleline/output isn't mounted into the deployment container.  Instead, the deployment container contains the project source:

    wercker build
    wercker deploy

Am I missing some command-line options necessary to successfully run the deploy step?

Complete debug output of build/deploy steps is here:

https://gist.github.com/ryanbauman/92c21c45563f386cbd56

**Comment by MaikuMori** [comment]
Same here. Is this a missing feature or we're doing something wrong?

**Comment by mariosotil** [comment]
One year after, I have the same problem, and there's no documentation about that. Are we doing something wrong?

**Comment by hatchan** [comment]
To do this you need to add the `--artifacts` to both the `wercker build` and the `wercker deploy` command. The `wercker deploy` command will use the latest results of the `wercker build` command. 

I've created an issue in our documentation section: https://github.com/wercker/docs/issues/409
