### ISSUE TITLE
Issue with getting packages from npm 

### ISSUE THREAD

**Issue by yamalight** [wercker/support#135]
Having issues with node wercker box [here](https://app.wercker.com/#buildstep/5601459471f137d02f01dd30).
Locally everything works just fine, remote box cannot install rx@3.1.x for some reason ([see logs](https://app.wercker.com/#buildstep/5601459471f137d02f01dd30)).
Are you using local npm cache or something?

**Comment by hatchan** [comment]
This `npm-install` step does have caching, see https://github.com/wercker/step-npm-install/blob/master/run.sh#L12-L15

You can clear your cache in the settings page of the project.

**Comment by yamalight** [comment]
@hatchan ok, after wiping cache (which is silly on its own) I don't have any more errors. 
but now it only installs normal dependencies, but not dev dependencies for some reason. and so "npm test" step fails ([see log](https://app.wercker.com/#buildstep/5603d69371f137d02f0526fe)). 

once again - locally (with plain npm and with wercker cli) everything worked and works fine.

**Comment by hatchan** [comment]
This is because the container itself exposes the `NODE_ENV=production`. This causes npm to only install normal dependencies.

**Comment by hatchan** [comment]
The easiest solution would be to do `export NODE_ENV=development` in a script step

**Comment by yamalight** [comment]
@hatchan but it works locally without any issues. whether i run it using wercker-cli or manually inside given docker container

**Comment by yamalight** [comment]
ah, right, it's me being an idiot - it uses already existing packages from node_modules :\
gonna try `export NODE_ENV=development` now...

**Comment by yamalight** [comment]
@hatchan okay, that fixed it. thanks for help!
