### ISSUE TITLE
Docker image not working with ENTRYPOINT that accepts /bin/bash

### ISSUE THREAD

**Issue by MartinsThiago** [wercker/support#136]
I'm having some trouble with an image where ENTRYPOINT receives a /bin/bash and works properly, at least locally on my linux

if I run locally `docker run test /bin/bash nvm install 0.10.0` I suppose it should behave as in the cloud.

Anyway I have to admit I wrote a tricky Dockerfile where entrypoint is declered: `ENTRYPOINT ["/bin/bash", "-c", "$@"]`

**Comment by hatchan** [comment]
I don't think you need to add the `"$@"` to the entrypoint. The cmd should just bee added to it.

We do not override the `entrypoint`, but we do override the `cmd`. We set the `cmd` to `/bin/bash`. 

If you have not resolved the issue, please send us the docker file and wercker.yml you are using.

**Comment by MartinsThiago** [comment]
Thanks for your support

I changed my Dockerfile and wercker :D.. any way here is the files I was
using

https://github.com/MartinsThiago/nvm-browsers/blob/1b0b1f30e5b2ec9295193cc0d47358661b36e617/Dockerfile

and

box: etiv/nvm-base

build:
  steps:
    - script:
        name: nodejs installation
        code: |
          nvm install 4.1.0
          nvm alias default 4.1.0
    - script:
        name: dependencies installation
        code: |
          npm install -s
          npm install -g gulp bower -s
          bower install --allow-root
    - script:
        name: tests preparation
        code: |
          apt-get -y update
          apt-get install -y software-properties-common
python-software-properties
          apt-get -y update
          add-apt-repository -y ppa:mozillateam/firefox-next
          apt-get install -y -q firefox openjdk-7-jre-headless
    - script:
        name: tests execution
        code: |
          export DISPLAY=0:0
          Xvfb :0 -ac -screen 0 1366x768x24 &
          gulp test
    - script:
        name: build execution
        code: |
          gulp
