### ISSUE TITLE
Building Docker during build with v2 API

### ISSUE THREAD

**Issue by bsideup** [wercker/support#15]
Hi!
Is it possible to build docker containers during build with new API? 

Thanks!

**Comment by hatchan** [comment]
The end result of a build is a docker container. You can retrieve the build by using the `wercker pull` command. These can be imported into your local Docker environment.

We're also working on Docker push functionality. This isn't finished yet, but will be finished shortly.

**Comment by bsideup** [comment]
Ok, thank you guys, we're waiting!
