### ISSUE TITLE
Wercker CLI not working (yet?)

### ISSUE THREAD

**Issue by JeanMertz** [wercker/support#150]
```
wercker version --beta
Version: 1.0.295
Compiled at: 2015-10-23 12:19:25 +0200 CEST
Git commit: db49e30f0968ff400269a5b92f8b36004e3501f1
No new version available
```

A couple of questions + observations:

* `wercker build --artifacts --store-local` does not seem to work as expected?

    ```
    --> Running step: prepare artifacts
    Storing artifacts
    Uploading file to S3
    ERROR Unable to upload file to S3
    ERROR Unable to upload file to S3
    ERROR Unable to upload file to S3
    ERROR Unable to store pipeline output Error=AccessDenied: Access Denied
    	status code: 403, request id: 
    --> Pipeline failed: 31.23s
    FATAL Step failed: store
    ```

* `wercker build --artifacts` causes a Go panic:

    ```
    --> Running step: prepare artifacts
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x68 pc=0x717a0]

    goroutine 1 [running]:
    main.func·025(0x0, 0x0)
    	/gopath/src/github.com/wercker/sentcli/main.go:894 +0x1f0
    main.executePipeline(0xa93a20, 0xc2080ad2c0, 0xc2080d8000, 0xc2080a1560, 0x0, 0x0, 0x0)
    	/gopath/src/github.com/wercker/sentcli/main.go:930 +0x2101
    main.cmdBuild(0xa93a20, 0xc2080ad2c0, 0xc2080d8000, 0xa939e0, 0x0, 0x0)
    	/gopath/src/github.com/wercker/sentcli/main.go:336 +0xcc
    main.func·001(0xc2080a8540)
    ```

* Q: how can I mimmic the exact same situation as is happening on wercker.com, calling `wercker build` and then using the artifacts from that build in one of the deploy pipelines?

* Q: is the source code for the wercker CLI available somewhere? Sometimes, as with the above panic, it's both handy to see what's exactly going on, and will help you if I could file a bug and/or PR to solve the problem.

**Comment by JeanMertz** [comment]
Turns out I was both *using it wrong*, and had a bug in the deploy scripts.

In fact, this seemed to work as expected using the Wercker beta CLI:

```
wercker build
wercker deploy --deploy-target rolling-update
```

including artifacts, no extra flags needed.

I'd still vote for:

* more detailed CLI documentation
* open-sourcing the CLI (but this is more a business decision)

:+1:

**Comment by faiq** [comment]
thanks for using the product and for the suggestions @JeanMertz 

i'm sorry we didn't get to your issue sooner.

we've definitely improved the CLI docs since late October and are working on a few more major rewrites to everything! keep an eye out for big news!
