### ISSUE TITLE
"Tarball is too big" error when deploying to `wercker-directory`

### ISSUE THREAD

**Issue by marshall007** [wercker/support#152]
```
Creating tar.
The size of the tarball is 8567721 bytes.
The maximum size is 8567721 bytes, cannot continue.
Package failed: Tarball is too big
```

The reported "maximum size" is always the exact size of the tarball itself. So two questions:

1. What is the true maximum size allowed?
1. Is there a workaround if the resulting tarball will be bigger than that?

In my particular case, I'm trying to bundle the `aws-cli` with my step so that it can be used during deployment. I don't have a lot of options for reducing the resulting artifact size.

**Comment by flenter** [comment]
The maximum size for __classic__ boxes is 1.5GB (compressed). A work-around for this would be to switch to the docker enabled environment and store your container on a docker registry (like [docker hub](https://hub.docker.com/) or [quay](https://quay.io/)).

**Comment by hatchan** [comment]
The max size of a step is 5 * 1024 * 1024 bytes. The size mentioned in the error message is indeed a bug.

**Comment by flenter** [comment]
We've rolled out an update that allows bigger steps (10MB) and fixes the incorrect maximum size message

**Comment by marshall007** [comment]
@flenter awesome, thanks! Do you guys `gzip` or otherwise compress the tarballs? It doesn't look like it, but doing so automatically would go a long way towards helping avoid the limit.

**Comment by hatchan** [comment]
@marshall007 we do use gzip compression
