### ISSUE TITLE
internal/docker-scratch-push step fails

### ISSUE THREAD

**Issue by vially** [wercker/support#155]
The `internal/docker-scratch-push` build step fails with error: "API error (500): Untar fork/exec /usr/bin/docker: argument list too long"

**Comment by vially** [comment]
I'm closing this because it seems to work properly now. Maybe it was a problem with the registry I was using.

**Comment by hatchan** [comment]
This was probably related to #102

**Comment by vially** [comment]
Definitely related. Thanks for the info!
