### ISSUE TITLE
deployments stuck on "get code" step

### ISSUE THREAD

**Issue by JeanMertz** [wercker/support#159]
We're seeing our deployments getting stuck in the initial "get code" step. The step never finishes (that is, I cancelled it after 3 minutes), and it keeps happening, but not all the time.

We're using 4 deploy targets that are started for every merge to master.

Deployments where working as expected yesterday. The only change we made was adding a fourth deploy target (which is almost equal to one of the others).

<img width="265" alt="screen shot 2015-11-04 at 07 47 27" src="https://cloud.githubusercontent.com/assets/383250/10931672/af535d94-82c9-11e5-8527-63715ee13587.png">

<img width="962" alt="screen shot 2015-11-04 at 07 48 39" src="https://cloud.githubusercontent.com/assets/383250/10931679/c67d9714-82c9-11e5-97c7-edf3ea40e9ef.png">

**Comment by flenter** [comment]
Can you enable support on the application and create a ticket with a link to the application (using the question mark button on app.wercker.com) or alternatively send an email to pleasemailus@wercker.com?

**Comment by chelarua** [comment]
I'm also seeing the same issue, deploy hangs at get code. I left it running for more than 30 mins and still wasn't finished. Yesterday it was fine though.

**Comment by flenter** [comment]
@chelarua Are you using the docker enabled infrastructure?

**Comment by chelarua** [comment]
We are using internal docker push command in the deploy step.
Ah and canceling and retrying the deploy worked so it is indeed not happening all the time.

**Comment by flenter** [comment]
@chelarua Can you enable support on the application you are seeing this with?

**Comment by chelarua** [comment]
yes

**Comment by flenter** [comment]
@chelarua Thank you, that helps a lot. We're still looking into it

**Comment by JeanMertz** [comment]
It seems the problems are no longer occurring for us. How about you @chelarua?

**Comment by flenter** [comment]
We rolled out a patch ~14 hours ago and were unable to reproduce the issue, good to hear you've not seen it either.
