### ISSUE TITLE
Build project locally fails with runtime error

### ISSUE THREAD

**Issue by emmenko** [wercker/support#16]
I wanted to try building the box locally by using the `wercker-cli` but somehow fails like this

```bash
$ wercker check-config
key path /Users/emmenko/.boot2docker/certs/boot2docker-vm/key.pem
Found box: emmenko/wercker-nodejs-karma_0.3.0
Found build section
$ wercker build
key path /Users/emmenko/.boot2docker/certs/boot2docker-vm/key.pem
############ Executing Pipeline ############

============== Running Step ===============
setup environment
===========================================
Running wercker version: 1.0.83 (Compiled at: 2015-03-25T21:26:17Z, Git commit: 25825ea2bad7cca66fcf38338985dfda218b1f2a)
Using config:
box: emmenko/wercker-nodejs-karma@0.3.0
# Build definition
build:
  # The steps that will be executed on build
  steps:
    - npm-install
    - npm-test
  after-steps:
    - hipchat-notify:
        token: $HIPCHAT_TOKEN
        room-id: $HIPCHAT_ROOM_ID

key path /Users/emmenko/.boot2docker/certs/boot2docker-vm/key.pem
Couldn't find image locally, fetching.
Pulling repository emmenko/wercker-nodejs-karma_0.3.0

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x3a16e]

goroutine 1 [running]:
main.(*Runner).GetBox(0x2088f4d40, 0x22088e5230, 0x20898b3c0, 0x2089cca00, 0x1, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/wercker/sentcli/runner.go:228 +0x44e
...
```

Any idea what's wrong? Or is the `wercker build` command intended to be used in another way?

Thanks

**Comment by hatchan** [comment]
The current beta version contains the fix for the nil reference. 

This is however not the cause of the problem. The problem is cause by the invalid box identifier.

The new ewok infrastructure uses docker containers, not the wercker boxes anymore. So you need to use a Docker container stored on Docker hub. 

More information regarding containers: http://devcenter.wercker.com/learn/containers/01_introduction.html

**Comment by emmenko** [comment]
Ah ok, so just to be clear we shouldn't use the boxes published to the wercker directory anymore? Instead create it in docker? (`wercker-box.yml` -> `Dockerfile`)

Thanks :)

**Comment by hatchan** [comment]
Yeah boxes on the wercker platform are only supported for are old infrastructure. 

You can locally build a docker container using docker build, and push that to the Docker Hub. Then you'll be able to use it in wercker. 

We are working on making it possible to push images from wercker.

**Comment by emmenko** [comment]
Cool, will do that. Many thanks! :)

**Comment by emmenko** [comment]
@hatchan sorry to bother you again but I'm having some weird behaviours.

So I've published a docker container (https://registry.hub.docker.com/u/emmenko/nodejs-karma/) and replace it as the box

```diff
-box: emmenko/wercker-nodejs-karma@0.3.0
+box: emmenko/nodejs-karma:v0.1.0
```

If I build it locally the container is loaded

```bash
$ wercker build
key path /Users/emmenko/.boot2docker/certs/boot2docker-vm/key.pem
############ Executing Pipeline ############

============== Running Step ===============
setup environment
===========================================
Running wercker version: 1.0.83 (Compiled at: 2015-03-25T21:26:17Z, Git commit: 25825ea2bad7cca66fcf38338985dfda218b1f2a)
Using config:
box: emmenko/nodejs-karma:v0.1.0
# Build definition
build:
  # The steps that will be executed on build
  steps:
    - npm-install
    - script:
        name: checks
        code: |
          node -v
          npm -v
    - npm-test
  after-steps:
    - hipchat-notify:
        token: $HIPCHAT_TOKEN
        room-id: $HIPCHAT_ROOM_ID

key path /Users/emmenko/.boot2docker/certs/boot2docker-vm/key.pem
Preparing Step: wercker-init
Preparing Step: npm-install
Preparing Step: script
Preparing Step: npm-test
Docker Container: 50cf0a636b4c98f99aa50a915bfd524b6287409419210e764e92454e7589ec0d
```

but when I pushed it to wercker it doesn't work

![screen shot 2015-03-27 at 12 29 22](https://cloud.githubusercontent.com/assets/1110551/6866901/fa200c7e-d47c-11e4-9baf-b1d81aebbbd2.png)


Any idea what I'm doing wrong?

**Comment by hatchan** [comment]
No worries, I'm here to help :smile_cat: 

It looks like the project is still using the old stack. You need to change this to 5. You can change this in the settings page of the project.

**Comment by emmenko** [comment]
Also if I build the container locally, when I run an npm command (which points to `./node_modules/.bin`) I get an error that the binary is not found

Example:

```javascript
// in package.json
"lint": "./node_modules/.bin/eslint .",
"test": "npm run lint && karma start --single-run"
```

When the `npm-test` step is run, it says

```bash
> @ lint /pipeline/source
> eslint .

sh: 1: eslint: not found

npm ERR! Linux 3.16.4-tinycore64
npm ERR! argv "node" "/usr/bin/npm" "run" "lint"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
```

But I never had this problem when the build runs on wercker environment. 

Have you had this problem before?

---

> You need to change this to 5

Thanks, will try that :+1:

**Comment by emmenko** [comment]
Ok, getting the same error now that I've upgraded to `Ewok 5`.

Hmm, will try to investigate more then...

**Comment by emmenko** [comment]
@hatchan so I did some digging and found out that in Docker `NODE_ENV` is set to `production`, so `npm install` doesn't work (didn't know that). 
So first thing to do is to set `NODE_ENV` to e.g. `test` to make it work.

However I found something weird. 
I tried first to do a fresh install a check the npm binaries

```yml
# this is the step
export NODE_ENV=test
echo $NODE_ENV
rm -rf node_modules && npm install
ls -ahl /pipeline/source/node_modules/.bin
/pipeline/source/node_modules/.bin/eslint .
```

which outputs

```bash
export NODE_ENV=test
echo $NODE_ENV
rm -rf node_modules && npm install
test
... # all npm logs
ls -ahl /pipeline/source/node_modules/.bin
total 8.0K
drwxr-xr-x  2 root root 4.0K Mar 27 03:13 .
drwxr-xr-x 31 root root 4.0K Mar 27 03:12 ..
lrwxrwxrwx  1 root root   23 Mar 27 03:12 eslint -> ../eslint/bin/eslint.js
/pipeline/source/node_modules/.bin/eslint .

set +v
```

So running `eslint` works. 
Then I changed the step to just do `npm install` (without `rm -rf node_modules`) and what I get is

```bash
...
ls -ahl /pipeline/source/node_modules/.bin
total 24K
drwxr-xr-x  2 root root 4.0K Mar 27 03:15 .
drwxr-xr-x 35 root root 4.0K Mar 27 03:14 ..
lrwxrwxrwx  1 root root   87 Mar 27 03:14 eslint -> /Users/emmenko/dev/src/my-project/_projects/my-project/node_modules/.bin/eslint
/pipeline/source/node_modules/.bin/eslint .
/pipeline/script-24ccc335-0d16-4b63-b4b2-c05575684118/run.sh: line 8: /pipeline/source/node_modules/.bin/eslint: No such file or directory
```

Why is the symlink different and why is it not working? Do you have any idea wha't happening here?

Thanks

**Comment by emmenko** [comment]
@hatchan Another thing I've noticed and I could't get to work is running karma tests with a browser like Chrome or Firefox.

If I use the classic stack (Andorian) with [this box](https://github.com/emmenko/wercker-nodejs-karma/blob/master/wercker-box.yml), tests run without problems and karma is able to spin up the browser.

```bash
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chromium 37.0.2062 (Ubuntu)]: Connected on socket KUNnuNAgcIVfroDE5T64 with id 99590579
```

However if I switch to docker (Ewok stack) with [this box](https://github.com/emmenko/docker-nodejs-karma/blob/master/Dockerfile), karma is not able to spin up the browser.

```bash
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
ERROR [launcher]: Cannot start Chrome

INFO [launcher]: Trying to start Chrome again (1/2).
ERROR [launcher]: Cannot start Chrome

INFO [launcher]: Trying to start Chrome again (2/2).
ERROR [launcher]: Cannot start Chrome

ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
```
This is a Docker problem apparently (I was able to reproduce it locally in the docker container) but still I can't figure out the problem.

Maybe you have any suggestion?

**Comment by emmenko** [comment]
Just FYI, the `Xvfb` wasn't starting inside the container, thus Chrome couldn't start.

@hatchan still would like to hear your opinion regarding the `node_modules` issue (see above). Thanks :)
