### ISSUE TITLE
Bundle install: The logs have been truncated (max log size: 1500000 bytes).

### ISSUE THREAD

**Issue by zedtux** [wercker/support#160]
I had 5 green builds, I have then added the `SimpleCov` gem to my Gemfile, then the build failed with the following:

```
bundle-install
  Command cancelled due to error
  The logs have been truncated (max log size: 1500000 bytes).
```

I don't understand what's going wrong here. Can you please help me ?

**Comment by hatchan** [comment]
Could you try clearing the cache of the application? You can do this in the settings page of the application

**Comment by zedtux** [comment]
Thank you ! This solved my issue !
