### ISSUE TITLE
increase concurrent deploys

### ISSUE THREAD

**Issue by JeanMertz** [wercker/support#163]
we've got four deploy pipelines on Wercker in one of our projects. I've noticed Wercker starting the first two deploys, but queuing the other two until one of the first two is completed.

Is there a way to increase the concurrent workers, to increase the deployment speed?

**Comment by flenter** [comment]
We can increase the concurrency for you. What's username of the owner of the projects?

**Comment by JeanMertz** [comment]
it's under the `Blendle` organisation. My username is `JeanMertz`. Nice to hear that this is a possibility :+1:

**Comment by flenter** [comment]
We've increased the concurrency for the Blendle organization to 4.

**Comment by JeanMertz** [comment]
Great to hear, thank you for the quick reply :+1:
