### ISSUE TITLE
pushing to two git branches 

### ISSUE THREAD

**Issue by TusharaFernando** [wercker/support#164]
Pushing to two git branches at the same time fails to pick up one of the pushes

**Comment by flenter** [comment]
Are you pushing to GitHub or Bitbucket?

**Comment by hatchan** [comment]
@TusharaFernando This is a known issue. When pushing multiple branches in a single push, we only create a single build. Current workaround would be to do multiple pushes, one for each branch.

**Comment by hatchan** [comment]
@TusharaFernando GitHub sends us multiple webhooks, so it should work there. And last week we fixed support for Bitbucket for this issue as well. Please reopen if this still is an issue.
