### ISSUE TITLE
Can't run downloaded tool

### ISSUE THREAD

**Issue by larsbrinkhoff** [wercker/support#169]
Application owner/name: larsbrinkhoff/forth-continuous-integration
Failed build: 5656b90d5d4798100d0560eb

I'm downloading a build tool.  The tarball extraction seems fine, and the file is in the expected loaction and is executable. However, running the tool results in a `not found` error message.

**Comment by hatchan** [comment]
I see you are downloading a i386 architecture binary, currently we only support amd64 architecture. This results in the error message that you got.

**Comment by larsbrinkhoff** [comment]
Oh, thanks!

**Comment by larsbrinkhoff** [comment]
This solves the problem:

    apt-get install lib32gcc1 libc6-i386
