### ISSUE TITLE
Bitbucket build status does not work for organizations

### ISSUE THREAD

**Issue by destitutus** [wercker/support#177]
Continuous integration for build status on bitbucket is broken for organizations but works for individual accounts

Status for org repo

![image](https://cloud.githubusercontent.com/assets/1736475/11589988/08cc419c-9a9e-11e5-8219-2666557c6408.png)

Status for individual repo
![image](https://cloud.githubusercontent.com/assets/1736475/11590010/3802df2a-9a9e-11e5-8266-04a7ae94e2fc.png)

**Comment by lindseybateman** [comment]
Thanks for creating the issue!

**Comment by brunoocasali** [comment]
:+1:

**Comment by hatchan** [comment]
@destitutus @brunoocasali We fixed this issue last week. Please reopen if this is still not working.

**Comment by brunoocasali** [comment]
@hatchan Thanks!

**Comment by ghristov88** [comment]
I have the same issue. I have a private repository which does not receive/change the build status. When I read this issue I create a public repository to run a test and there everything works like it is supposed to do. Is this a BitBucket issue or it is CI plugin related?
