### ISSUE TITLE
Builds not running

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#179]
Looks like builds aren't running when I push commits.

**Comment by hatchan** [comment]
We're having a database issue. We're rebuilding an index to solve the issue. Sorry for the inconveniences.

**Comment by sasha-s** [comment]
Any progress with it?
I saw a few builds skipped entirely.
I was able to trigger the latest one by re-sending a github webhook (so at least Wercker shows the latest commit in Builds), but the build appears to stuck ( Waiting for build to start ).

**Comment by flenter** [comment]
The problem's resolved (though we're still monitoring), However, there's a fairly large backlog which we're processing a.t.m. sorry for the inconvenience!

**Comment by jakirkham** [comment]
Seems to be working fine again. Thanks for getting this back up and running guys.

**Comment by BeOleg** [comment]
And it happens again...
