### ISSUE TITLE
Can't delete user

### ISSUE THREAD

**Issue by jamesdixon** [wercker/support#181]
Hi,

I'm trying to remove a user from my team and see the following message:

![image](https://cloud.githubusercontent.com/assets/110114/11912034/474734b8-a5e8-11e5-9ded-a01f1f6db69b.png)

What do I need to do to fix this?

Thanks!

**Comment by flenter** [comment]
On applications owned by organizations a member of the owners team has a special role. His/her user information is used to make certain api calls to GitHub/Bitbucket. By default, this is the user that adds the application to the organization. Users who are linked to an application like that can't be removed from the owners team. You can change the 'api user' in the settings/options of an application (nearly at the bottom of the page).

<img width="1000" alt="application settings - options" src="https://cloud.githubusercontent.com/assets/473804/11924952/dfcaf880-a7b6-11e5-8b92-ee3b63eec7aa.png">

**Comment by jamesdixon** [comment]
Worked perfectly. Thank you!
