### ISSUE TITLE
Building data-only container

### ISSUE THREAD

**Issue by boedy** [wercker/support#182]
I wan't to build a data-only container which exposes some volumes which enables other containers to use volumes-from. If I'm not mistaken both internal/docker-push and internal/docker-scratch-push don't support this. Is there workaround for this?

**Comment by hatchan** [comment]
It is now possible to use volumes, specify them by using the `volumes` property in the internal/docker-push step. See http://devcenter.wercker.com/docs/steps/internal-steps.html
