### ISSUE TITLE
GET https://registry.hub.docker.com/v1/repositories/wercker/default/images returned 404

### ISSUE THREAD

**Issue by franciscocpg** [wercker/support#185]
I am trying to build a custom step and getting the error `GET https://registry.hub.docker.com/v1/repositories/wercker/default/images returned 404`
This is the wercker app:
https://app.wercker.com/#buildstep/568bbc1c81fd0f502205f151

**Comment by hatchan** [comment]
Currently it is not possible to publish steps using the Docker enabled stack. You need to switch the application back to V1, you can do this in the options of the application. 

(Note: after publishing the step, you can either use it in the legacy stack or the Docker enabled stack)

**Comment by franciscocpg** [comment]
@hatchan, I forgot about this. Thank you.
Just one more question, is it possible to simulate this behaviour using with *werccker cli* using `wercker build'

**Comment by hatchan** [comment]
It is not possible to run our legacy stack using the wercker cli. Closing this issue, if you have any other questions open a new issue.
