### ISSUE TITLE
Not able to delete any application

### ISSUE THREAD

**Issue by peek4y** [wercker/support#189]
I'm unable to delete any existing application.

I keep getting this error

``` An error occured while deleting the application. ```

Also, unable to create app via BitBucket.

**Comment by lindseybateman** [comment]
Thanks for reporting, could you see what for error you're getting in the console.

**Comment by peek4y** [comment]
Sorry, somehow the authorization to bitbucket got revoked, so it won't let me delete or create app via BitBucket, I re-authorized with Bitbucket and it works fine.

Thanks for the quick response.

**Comment by lindseybateman** [comment]
Great @peek4y, thanks for your reply.
