### ISSUE TITLE
A way to build and deploy multiple containers from a single github webhook

### ISSUE THREAD

**Issue by let4be** [wercker/support#190]
Hi!
I'm having multiple projects within the same git repo(golang),
when I'm doing commit I'd like to compile all of them using go install which first checks if the target changed(wercker cache)
I can easily do this now, the tricky part is how to deploy multiple executables produced on the build step into separate docker containers and push to separate dockerhub repositories
Any ideas?

**Comment by hatchan** [comment]
We're working on a new feature which allows for multiple builds, with different steps for git webhooks.

Currently it is not possible to have different boxes per deploy target.

**Comment by stepanstipl** [comment]
+1 I would be very much interested in this possibility as well

**Comment by flenter** [comment]
sorry for the delayed response. but we've released this feature (a while already). It's called workflows, see for more information: http://blog.wercker.com/introducing-wercker-workflows
