### ISSUE TITLE
deploy "unknown" emails after moving to docker system

### ISSUE THREAD

**Issue by PepijnK** [wercker/support#194]
Hi,

I've moved my projects from Classic wercker to Docker style projects, and now I get emails which have unknown as build results.
Also deploy emails are now "unknown" instead of "passed" or "failed"

Any idea how to resolve this?

**Comment by lindseybateman** [comment]
Hi,

Thanks for reporting this! We have released a fix for this issue, could you confirm that?

Cheers,
Lindsey

**Comment by PepijnK** [comment]
yes it is fixed.
