### ISSUE TITLE
Every build is going to be queued even when there is no running build

### ISSUE THREAD

**Issue by 5t111111** [wercker/support#207]
Every build is going to be queued even when there is no running build. We have tried to abort builds and re-push to GitHub to trigger new builds but no luck so far. We have also enabled "Support" in setting panel so that could you solve this problem.

- wercker environment: hosted
- application owner: yochiyochirb (organization)
- application name: kajaeru (ID: 56de5c2e9d5cf1b573463924)
- The ID of the build or deploy that failed: not provided yet

**Comment by mies** [comment]
hi @5t111111 we're currently investigating this issue and will update you. sorry for the inconvenience!

**Comment by hatchan** [comment]
Everything should be back to normal. Please reopen if you're still experiencing this issue.

**Comment by 5t111111** [comment]
l really appriciate your help!
