### ISSUE TITLE
Run one deploy target after another

### ISSUE THREAD

**Issue by otaviosoares** [wercker/support#208]
I want to push an image to dockerhub and use it to deploy a new version of my app using kubectl.
So I have 2 targets: dockerhub and rolling-update.

Is it possible to start the rolling-update step automatically but just after the dockerhub image has been pushed?

I tried to enable auto deploy for both, they run simultaneously though.

My wercker.yaml https://gist.github.com/otaviosoares/4854e8e27ab3cf772f77bbe9750eaf3b

Thank you

**Comment by mies** [comment]
apologies for the delayed response! We've just launched [Wercker Workflows](http://wercker.com/workflows) which enables you to do exactly that.

Check out the sample repo and wercker.yml here:
http://github.com/wercker/workflows-kubernetes-demo
