### ISSUE TITLE
Cannot create step application, "Step creation failed"

### ISSUE THREAD

**Issue by ernoaapa** [wercker/support#210]
Hi,
I cannot create new Step from the Wercker web UI under our organisation. It just prints "Step creation failed. Try again later".

Source of the step is here: https://github.com/SharperShape/wercker-step-cache

In Chrome developer tools, I can see failed request:
```
# POST https://app.wercker.com/api/v2/applications
# Body
{"scmProvider":"github","scmOwner":"SharperShape","scmName":"wercker-step-cache","privacy":"public","owner":"sharpershape","stack":"1"}

# Response 422 Unprocessable Entity
# Body
{"statusCode":422,"error":"Unprocessable Entity","message":"Invalid owner id"}
```

Additional information:
- wercker environment: hosted

**Comment by ernoaapa** [comment]
And just tested that I were able to create new step under my own profile from my own fork (ernoaapa/wercker-step-cache).

I would like to create it under our organization so it's not depending anyway to my account.

**Comment by akupila** [comment]
@ernoaapa Sorry for the late response, completely didn't notice this issue. 
The problem has been fixed and you can now create steps for organizations too.
