### ISSUE TITLE
'Report to SCM' check box does not save

### ISSUE THREAD

**Issue by mattetre** [wercker/support#211]
Migrated to workflows today. The status of the build was no longer reflected in GitHub PRs. Tried to check the 'Report to SCM' (thinking this may fix the GitHub problem) under Setting --> Workflows --> Pipelines --> build - but it does not seem to save. 

- Check the box
- Click update
- Refresh the page and now box is unchecked

![screen shot 2016-05-10 at 2 58 02 pm](https://cloud.githubusercontent.com/assets/1724838/15159149/197d8af6-16c1-11e6-8c6e-73c732e131d1.png)
![screen shot 2016-05-10 at 3 06 13 pm](https://cloud.githubusercontent.com/assets/1724838/15159150/1ba42998-16c1-11e6-8b7b-28cb71048574.png)

**Comment by flenter** [comment]
Fix is ready, will be rolled out in a bit

**Comment by flenter** [comment]
Fix is live. You do have to refresh any open tabs for it to work. 

And also: thank you for reporting this & sorry for the inconvenience!

**Comment by mattetre** [comment]
👍 looks good! thank you for the quick fix
