### ISSUE TITLE
Pull requests won't build using workflows

### ISSUE THREAD

**Issue by moritzzimmer** [wercker/support#212]
We migrated one of our projects to the new workflow setup. Everything works fine for workflows triggered by changes in the master branch. However building pull request fails in the **get code** step.

Any ideas?

Here is the error message (checking out locally works fine):
```
git clone --depth=50 --quiet --progress --no-single-branch git@github.com:WeltN24/foo.git ./
remote: Counting objects: 542, done.        
remote: Compressing objects: 100% (276/276), done.        
remote: Total 542 (delta 198), reused 475 (delta 151), pack-reused 0        
Checking connectivity... done.
git checkout -fq cee9fd00b54ccd34d328816433dc88c9c0eb170c
fatal: reference is not a tree: cee9fd00b54ccd34d328816433dc88c9c0eb170c
```

**Comment by AndreCapelache** [comment]
Same problem.

**Comment by flenter** [comment]
@moritzzimmer We're about to roll out a fix for this issue. Thank you for reporting and sorry for the inconvenience!

**Comment by moritzzimmer** [comment]
@flenter works now, thx!
