### ISSUE TITLE
Workflow not trigger changes on branch develop

### ISSUE THREAD

**Issue by AndreCapelache** [wercker/support#213]
Hi.

On the new workflow setup, my commits on branch develop (private Bitbucket) is not trigger changes.

Thanks

**Comment by AndreCapelache** [comment]
it's the same problem then #212

**Comment by ajagnanan** [comment]
Not sure whats going on, but I have bitbucket online using teams and pushes to the repo do not trigger builds. I tried manually triggering a build through the api with no luck also.

**Comment by flenter** [comment]
I think #212 is not the same. There runs/builds are being created. While here (I think) nothing is created. We have a fix for bitbucket repos where pushes wouldn't trigger runs when the bitbucket accounts were not linked to a wercker account. The fix should be rolled out to all servers with the hour

@ajagnanan Is your application on wercker also using workflows?

**Comment by flenter** [comment]
@AndreCapelache & @ajagnanan almost forgot: thank you for reporting and sorry for the inconvenience!

**Comment by AndreCapelache** [comment]
@flenter very thanks!!! it's work now!!

**Comment by ajagnanan** [comment]
@flenter working now, thanks!
