### ISSUE TITLE
Error creating workflow - "Error creating hook"

### ISSUE THREAD

**Issue by Bruno-de-l-Escaille** [wercker/support#215]
I can't create workflow for my app "apittp" I get error creating hook.

<img width="461" alt="screen shot 2016-05-12 at 15 25 07" src="https://cloud.githubusercontent.com/assets/3229307/15217931/9d5f4676-1855-11e6-9579-6dd7577b0354.png">

Yesterday i't works fine!

Any help please! this bug has stoped all my builds.

**Comment by flenter** [comment]
Can you enable support?

**Comment by flenter** [comment]
We've released a fix
