### ISSUE TITLE
apps are not showing continuous-integration/wercker details in PR's on github

### ISSUE THREAD

**Issue by metral** [wercker/support#219]
Two new wercker apps of mine: `corekube/git-sync` & `corekube/hugo` are not displaying the `continuous-integration/wercker` detail box [as seen here](https://dl.dropboxusercontent.com/spa/k3166uk8y4ehmla/5tji2fjv.png) from another working app I have, even though restrictions are granted and the details are in fact functional in my other apps.

The only thing I can think of is that the two new apps were deleted and recreated today, with the same name, and I'm not sure if that has anything to do with recent changes to `wercker.com` or not.

Any advice would be appreciated to show the proper CI details for my PR's - thanks!

Additional information:

- wercker environment: <hosted>

**Comment by hatchan** [comment]
Could you check the `build` pipeline and set `Report to SCM` to true

**Comment by metral** [comment]
@hatchan thank you! that plus re-granting third-party access was required to get things working for me
