### ISSUE TITLE
Wercker box deploy fails on package and store phase

### ISSUE THREAD

**Issue by Mil0dV** [wercker/support#22]
We're seeing consistent failing of the package and store phase of the deploy to the registry of one of our boxes. The specific error we're seeing:

package and store
[object Object]
Removing working directories.
Creating tar.
Package failed: Error: Command failed: tar: /var/lib/lxc/builde23510d8-62e1-4cc8-99a8-18bbbf14b900: Cannot chdir: No such file or directory
tar: Error is not recoverable: exiting now

The box in question is: https://app.wercker.com/#applications/554600d1dc16db447927eead/tab/deployment , I've enabled support on it. After some testing I think I've pinpointed the issue: it seems any box that inherits inherits: wercker-labs/docker can't be stored.

This is pretty critical for us since we need docker, and since that's not supported on the Ewok stack this seems out only option on Wercker.

Thanks for your assistance on this!

**Comment by flenter** [comment]
Unfortunately, the wercker-labs/docker environment can't be inherited from. It is not the same type of container as we're using in the classic environment, this means it can't be extended in the same way.
