### ISSUE TITLE
Commit links for Bitbucket are to repo source as opposed to commit

### ISSUE THREAD

**Issue by BenBrostoff** [wercker/support#222]
It would be nice if the links to individual commits for Bitbucket on wercker builds went to the actual commit as opposed to the repo at that commit. What I mean here is that Bitbucket links on wercker are currently https://bitbucket.org/my-org/my-repo/src/<commit-hash>, as opposed to https://bitbucket.org/my-org/my-repo/commits/commit-hash.

If more users prefer the repo source to the commit diff, I completely understand - just an opinion :-).

**Comment by hatchan** [comment]
Linking to the commit does sound better, I've created a PR for this.

**Comment by hatchan** [comment]
Thanks again for the feedback, will deploy the change later today.
