### ISSUE TITLE
Can not clone a public repo in a pipeline

### ISSUE THREAD

**Issue by ertrzyiks** [wercker/support#223]
I'm using workflows and want one of my steps in .yml file is cloning a public repository from github.

`git clone git@github.com:<user>/<repo_slug>.git .publish`

command fails with an error:
```
Cloning into '.publish'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by hatchan** [comment]
You need to make sure that the hostkey for github.com is trusted. One way of doing this is using the [`add-to-known_host`](https://github.com/wercker/step-add-to-known_hosts).

**Comment by ertrzyiks** [comment]
@hatchan it works, thanks!
