### ISSUE TITLE
Page doesn't open

### ISSUE THREAD

**Issue by ernoaapa** [wercker/support#224]
"Failed" build link in the email, opens page which is empty. I need to go to the applications -page and then select the failed build to see the build. 

I bet there is also other cases too when I get the "blank page", browser force refresh helps sometimes, sometimes need to go through the application page. Really annoying.

Additional information:

- wercker environment: hosted
- OS: OSX, Chrome 50.0.2661.86 (64-bit)

**Comment by flenter** [comment]
thank you for reporting... We're working on a fix!

**Comment by flenter** [comment]
A fix for this will be rolled out later today. New emails will have the correct link.
