### ISSUE TITLE
Wercker VM local run: no space left on device

### ISSUE THREAD

**Issue by autodidaddict** [wercker/support#225]
When I run the wercker build locally, it runs out of space when trying to fire up the mongo service. This did not happen yesterday, but it does today. It doesn't appear to be happening on Wercker's website. I have checked and I have plenty of disk space left.

Additional information:

- wercker environment: local
- OS: mac
- Docker environment: regular docker installer (docker, docker-machine, virtual box)
- Docker machine driver used: virtualbox

[My gist](https://gist.github.com/autodidaddict/1d716ef261f119e6473cbc81d101a158)

**Comment by flenter** [comment]
Do you have many docker containers / images on your machine? Maybe the virtual machine is running out of disk space (even though your mac still has enough disk space).

You can check this by running:
```
 docker-machine ssh default -- df -h
```

**Comment by autodidaddict** [comment]
I just purged all my images and containers and it fixed this. I only had 1 more container than I normally run with, but I guess this is what pushed me over the edge. Sorry for the inconvenience.

**Comment by flenter** [comment]
No problem! Happy to see it resolved so quickly.
