### ISSUE TITLE
Wercker API build trigger create a new build, but build is not started.

### ISSUE THREAD

**Issue by amondnet** [wercker/support#228]
http://devcenter.wercker.com/api/endpoints/builds.html

**Trigger a new build** is not worked.

Build is created successfully, but build is not started. 

```
curl -H "Authorization: Bearer authoriztionToken" \
     -H "Content-Type: application/json" \
     -X POST \
     -d "{\"applicationId\":\"5751af493abbc9f50c12cea1\", \"branch\":\"$BRANCH\", \"commitHash\":\"$COMMIT\"}" \
     "https://app.wercker.com/api/v3/builds"
```

![2016-06-07 14 08 44](https://cloud.githubusercontent.com/assets/1964421/15846637/1c28eeb2-2cba-11e6-879e-8573b1c543f5.png)

Additional information:

- wercker environment: hosted

**Comment by hatchan** [comment]
When using the new workflows stack, you need to use the new `https://app.wercker.com/api/v3/runs` endpoint. The payload is the exact same. The documentation is lacking behind a bit.

**Comment by amondnet** [comment]
@hatchan Thanks, it works.

+ pipelineId is also required.
