### ISSUE TITLE
Ewok infrastructure store step fails sometimes

### ISSUE THREAD

**Issue by timflapper** [wercker/support#23]
We recently switched over to the new Ewok infrastructure and everything seems to be working great. except that the "store" step fails intermittently. Here is where it stopped on our last build:
![](http://img.springe.st/2015_05_07_10_01_09_8fnu9.png)

**Comment by mies** [comment]
Hi Tim, we've improved our infrastructure over the last two weeks. Are you still experiencing the failures on the store step?

**Comment by flenter** [comment]
No feedback yet. Closing the issue for now
