### ISSUE TITLE
Creating registry name not done correctly

### ISSUE THREAD

**Issue by MichaelVorster** [wercker/support#236]
Hi,

I want to push a container to Google cloud in my deploy pipeline:

deploy:
    box: python:3.5
    steps:
     - internal/docker-push:
        username: $KUBERNETES_USERNAME
        password: $KUBERNETES_PASSWORD
        registry: https://gcr.io
        repository: gcr.io/project

However, when I run the deploy pipeline Wercker creates the full URL as 'https://gcr.io/v1/repositories/project'  How do I remove the 'v1/repositories' part?

**Comment by Tonnu** [comment]
Hi there, you can simply append `/v2` to your registry URL (so in your case `https://gcr.io/v2`)
