### ISSUE TITLE
Building multiple docker images with 1 artifact

### ISSUE THREAD

**Issue by PepijnK** [wercker/support#237]
Hello,
I'm trying a few days now to get Wercker pushing and deploying multiple, lean docker images containing a JAR each. These JAR's are a product of a multi module maven build during the build pipeline.

Somehow my images have the full pipeline contents in it, which makes them massive (~800mb). My built JAR's are just 80mb each... I would like to create the smallest docker images possible and deploy them in my ECS demo env so I don't care about all the intermediate stuff, maven repo's, compiled class filed, etc.

I've tried:
- Cleaning all pipeline directories after copying the artifacts to '/'. It gives me the possibility to push one JAR. But you throw away the whole wercker env, the build/steps/cache dir, this made my next step fail (deploy).
- Do 'rm $WERCKER_OUTPUT_DIR/*' and add a JAR before the internal/push script. Hence no luck, 
my images are 900mb! 

I have the feeling Wercker isn't really meant for compile languages like java, all the env vars with contradicting documentation (use DOCKER_CACHE, OUTPUT, SOURCE?? What is wiped and what remains through the pipeline steps..etc). It makes it so cumbersome to only add stuff you want to the result image.

Currently I have it working in CircleCI, but I would like to use Wercker as I really like Wercker-Workflows.

**Comment by Tonnu** [comment]
Hi @PepijnK, would you mind posting your wercker.yml in a gist?

**Comment by PepijnK** [comment]
This was an attempt as described by option 1 (wipe Wercker stuff, put jars in /, run docker-push): 
https://gist.github.com/PepijnK/a976bdef50b8ccdbcc3dfcc217df74e9

However, this broke further wercker features as I wipdes the wercker dir. Also, I get 2 JARS in both images.

**Comment by Tonnu** [comment]
I've created a gist about how I think you should tackle this problem. I've left some comments inside on how you should set up your Workflows on the Wercker platform as well. https://gist.github.com/Tonnu/0902757325dba334a32dcf8e0458cd80

Basically you want to split up your docker pushes into two separate pipelines. Both of those pipelines should get triggered by the build pipeline in parallel. 

So your workflow will look like this:

```
build ---> push-dev-api
      |
      |--> push-dev-auth
```

**Comment by PepijnK** [comment]
That looks promising, I get 46 mb per image..! BTW, I now do
 rm -rf the /pipeline
before the push...
That is the only place things get stored right?

**Comment by Tonnu** [comment]
yes, `/pipeline` is the only place Wercker stores information. Closing the issue, let me know if you have any other questions ;).

**Comment by PepijnK** [comment]
Could it be that my subsequent pipelines are not working now?
It instantly fails with:

X Auto trigger from Pipeline "push-api" to Pipeline "dev-deploy-api"
0 secondsX get code

(This is what was experienced and described in the issue)
