### ISSUE TITLE
All of my builds are stuck

### ISSUE THREAD

**Issue by KazW** [wercker/support#238]
No matter how many times I abort my build and restart it, or push new commits, every build I run gets stuck. I think it may just be my account, because it's happening to 2 of my projects, each using different images and languages. Even re-running old builds that ran successfully at first, now get stuck. I didn't change any project settings, just pushed new commits.

One of my projects is public, and as you can see, even though all the steps are done, it's still "waiting to start". https://app.wercker.com/#KazW/Hermes-rails/build/5777da29b45c977302023af4

**Comment by inouetakuya** [comment]
I am in the same trouble.

(my application is private)

https://app.wercker.com/#applications/573b233dd99505465711a069

![160703-0001](https://cloud.githubusercontent.com/assets/634357/16543148/2c1f10ba-4102-11e6-95ca-1354f39775b2.png)

----

It is bitter for me because github can not receive report of build.

![160703-0002](https://cloud.githubusercontent.com/assets/634357/16543152/71c574e2-4102-11e6-85c8-9fc881f3901f.png)

**Comment by flenter** [comment]
We've located the problem, new workflows should be updated correctly. Can you confirm this is working for you again?

**Comment by inouetakuya** [comment]
Wow, I have checked that new workflows have beeen updated correctly!! Thank you very much!!!

**Comment by inouetakuya** [comment]
@flenter 

Wow, I have checked that new workflows have beeen updated correctly!! Thank you very much!!!

**Comment by ChallahuAkbar** [comment]
Yup, was having the same problem last night but new runs are properly updating their status after completion.

**Comment by KazW** [comment]
My builds are now reporting the correct status that matches their progress: "waiting to start"

However, I've been waiting 15 minutes, the builds haven't started yet. :pensive:

**Comment by KazW** [comment]
This issue has been resolved. Thanks!

**Comment by chankeypathak** [comment]
Facing the same issue. Stuck on "waiting to start" from past 6 hours.

**Comment by laudeco** [comment]
I have the same issue.

**Comment by flenter** [comment]
@laudeco can you open a ticket using the green question mark button on app.wercker.com? And provide some more details, like which app isn't running (ideally with support enabled for that app)?  That way we can more easily find out why things aren't working for you!
