### ISSUE TITLE
wercker cannot handle Docker containers with an ENTRYPOINT

### ISSUE THREAD

**Issue by tvaughan** [wercker/support#24]
This one has prevented me from using ewok since it was introduced. I've The problem appears to be that wercker can't handle a docker image that has an ENTRYPOINT. I've also emailed these details to pleaseemailus@wercker.com, but there's been no resolution to this problem yet. This fails locally and on wercker.com too.

For example, given this wercker.yml:

    box: tvaughan/ubuntu:8675309
    build:
      steps:
        - script:
            code: |
             true

and this Dockerfile:

    $ cat Dockerfile
    FROM ubuntu:14.04
    MAINTAINER "Tom Vaughan <tvaughan@tocino.cl>"

it works:

    $ wercker b
    --> No Docker host specified, checking: unix:///var/run/docker.sock
    --> Executing pipeline
    --> Running step: setup environment
    Pulling repository tvaughan/ubuntu

    --> Running step: wercker-init
    --> Running step: script
    --> Steps passed
    --> Pipeline finished

But with this Dockerfile:

    $ cat Dockerfile
    FROM ubuntu:14.04
    MAINTAINER "Tom Vaughan <tvaughan@tocino.cl>"
    ENTRYPOINT ["/bin/bash"]

it does not work:

    $ wercker b
    --> No Docker host specified, checking: unix:///var/run/docker.sock
    --> Executing pipeline
    --> Running step: setup environment
    Pulling repository tvaughan/ubuntu

    ERROR --> Step failed: setup environment
    Command cancelled due to error
    ERROR Command cancelled due to error
    WARNING Box container has already stopped.

**Comment by raphiz** [comment]
Same problem here. This is a blocker when using or inheriting from third party images. There is also no way to my knowledge to "unset" the entrypoint value.

**Comment by jakirkham** [comment]
Good to know its not just me. Same problem.

**Comment by jakirkham** [comment]
It appears this may be fixed. At least, I was able to run a test recently using a Docker container with an ENTRYPOINT. I'd be curious to know if the two of you also saw this change.

**Comment by raphiz** [comment]
I do still have this issue - tried it out with [this image (grahamc/jekyll)](https://registry.hub.docker.com/u/grahamc/jekyll/)

**Comment by tvaughan** [comment]
I still have this problem too.

**Comment by hatchan** [comment]
@tvaughan: I've create the same image using your Dockerfile instruction, and ran into the same issues that you did. I also tried to run the container locally and found out it also fails locally:

```
FROM ubuntu:14.04
MAINTAINER "Benno <benno@wercker.com>"
ENTRYPOINT ["/bin/bash"]
```

```
$ docker build -t bvdberg/issue-24 .
$ docker run -it --rm bvdberg/issue-24 "/usr/bin/env"
/usr/bin/env: /usr/bin/env: cannot execute binary file
```

While the stock `ubuntu` image does work:

```
$ docker run -it --rm ubuntu  "/usr/bin/env"
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=8681ec36674d
TERM=xterm
HOME=/root
```

I came across this stackoverflow question which explains the usage of the entrypoint command: http://stackoverflow.com/a/21564990/3801979. 

So after changing the Dockerfile it did work:

```
FROM ubuntu:14.04
MAINTAINER "Benno <benno@wercker.com>"
ENTRYPOINT ["/bin/bash", "-c"]
```

```
$ docker run -it --rm bvdberg/issue-24 "/usr/bin/env"
HOSTNAME=a66ea03bca60
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
_=/usr/bin/env
```

@jakirkham: Do you remember which image caused the problems? 

@raphiz: Thanks I'll investigate that image next.

**Comment by hatchan** [comment]
@raphiz: It looks like that `grahamc/jekyll` overrides the entrypoint to a non-shell binary. 

This works when using it with `docker run --rm -v "$PWD:/src" grahamc/jekyll build`, but wercker requires a shell (such as bash or sh) as an entrypoint. 

I've created a pull request to add the ability to override the entrypoint, which allows you to do something `/bin/bash`. I'll let you know when it is merged and released.

**Comment by tvaughan** [comment]
@hatchan Thanks for looking into this. However, I don't understand the solution. The way to override the entrypoint is like so:

```
$ cat Dockerfile 
FROM ubuntu:14.04
MAINTAINER "Tom Vaughan <tvaughan@tocino.cl>"
ENTRYPOINT ["/bin/bash"]
$ docker run --entrypoint /usr/bin/env --rm -i -t tvaughan/issue-24
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=f48b5cd5ca7f
TERM=xterm
HOME=/root
```

Do you mean to say that wrecker requires "bash -c" to be then entrypoint?

**Comment by hatchan** [comment]
@tvaughan Yes the entrypoint need to be `/bin/bash -c`. Which you can do locally by using `--entrypoint` flag, or

**Comment by hatchan** [comment]
by using the following ENTRYPOINT in the dockerfile: 
```
ENTRYPOINT ["/bin/bash", "-c"]
```

**Comment by hatchan** [comment]
Also, the ability to override the entrypoint through the wercker.yml will come later, probably next week

**Comment by tvaughan** [comment]
> On Jul 23, 2015, at 14:57, Benno van den Berg <notifications@github.com> wrote:
> 
> Also, the ability to override the entrypoint through the wercker.yml will come later, probably next week
> 
Ok. But why require everyone to set the entrypoint to 'bash -c'? Shouldn't wercker forcibly override the entrypoint if this is what it requires to work?

**Comment by hatchan** [comment]
Well you can use `bash`, but you can also use `sh` or maybe even other shells. But we cannot assume that `bash` is install, most containers do not have it. So we use whatever Docker has configured, which is `/bin/sh -c` by default.

**Comment by jakirkham** [comment]
@hatchan, thanks for looking into this. Since I ran into this problem, I have made a number of changes to the original image. I think the problem was not so much the entrypoint, but having a non-root user as the normal user in the container. However, I have stopped doing this since.

**Comment by tvaughan** [comment]
> So we use whatever Docker has configured, which is /bin/sh -c by default.

I wouldn't say that Docker does this by default, but rather the official Ubuntu container does. I assume, based on nothing more than my own anecdotal experience, that more than half of the containers on the Docker Hub have an entry point other than `bash -c` or `sh -c`. If the container has an entrypoint that is unsupported by wercker, I would expect wercker to try to set it to something workable and complain loudly if it cannot.

**Comment by raphiz** [comment]
@hatchan Thanks for your investigations!
I really like the idea brought up by @tvaughan. This makes a lot of sense from a usuability point of view. 
@jakirkham I figured this out as well - wercker does not seem to work with non-root users - at least when i tried it out back in May.
It would be nice to find these pitfalls in the docs...or at least get a clear error message.

**Comment by hatchan** [comment]
The stackoverflow post mentions that `/bin/sh -c` is the default. So the entrypoint is defined as follows: 

- Override value through the cli or through the rest api
- ENTRYPOINT value as defined in the Dockerfile
- Default value of `/bin/sh -c`

Currently we require an binary which is able to run the cmd value (where the cmd value should be a shell, which we default to `/bin/bash`).

I agree that the current error message is lacking, unfortunately it is quite difficult to retrieve the exact cause of the error. But having a page in our devcenter about this is already a good first step.

**Comment by jakirkham** [comment]
>  If the container has an entrypoint that is unsupported by wercker, I would expect wercker to try to set it to something workable and complain loudly if it cannot.

@tvaughan, I think I would dislike this being set for me. I would rather have a complaint if this is the case.

**Comment by jakirkham** [comment]
> But having a page in our devcenter about this is already a good first step. 

@hatchan, that sounds great!

**Comment by hatchan** [comment]
What currently is created in the cli is that we do remove the entrypoint, and require a shell as the cmd. If no cmd is provided we try `/bin/bash`. If you readlly need to specify a entrypoint you can always overwrite it.

It's a bit more hassle for users that do need to update it, but for the majority this will give a better experience.

That said, I think that overwriting the entrypoint should be avoided. The only reason you should do this is when using the container for executing tools, or have services in there (but those can also use the `cmd`).

For example I created a ping box with the following dockerfile:

```
FROM ubuntu
ENTRYPOINT ["/bin/ping"]
CMD ["localhost"]
```

If you create and call this container with following signature it will start pinging to localhost:

```
$ docker run -it --rm bvdberg/ping
PING localhost (127.0.0.1) 56(84) bytes of data.
...
```

But you can also provide a "`cmd`", which will just turn into arguments to the entrypoint:

```
docker run -it --rm bvdberg/ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
...
```

**Comment by jakirkham** [comment]
> What currently is created in the cli is that we do remove the entrypoint

@hatchan, can you please explain this point? I would really like to keep my own entrypoints when I specify them.

**Comment by tvaughan** [comment]
> That said, I think that overwriting the entrypoint should be avoided. The only reason you should do this is when using the container for executing tools, or have services in there (but those can also use the cmd).

The documentation says otherwise - https://docs.docker.com/articles/dockerfile_best-practices/

    The best use for ENTRYPOINT is to set the image’s main command, allowing that image to be run as though it was that command (and then use CMD as the default flags).

This shows that the entrypoint for the official Postgresql image is the postgresql binary.

**Comment by tvaughan** [comment]
> For example I created a ping box with the following dockerfile:

Yup. I'm aware of the pattern.

    https://github.com/tvaughan/docker-ansible
    https://github.com/tvaughan/docker-go
    https://github.com/tvaughan/docker-transcrypt

**Comment by hatchan** [comment]
@tvaughan Aah I see, thanks. I'll make it optional for service boxes, but for the main box we need to be able to launch a shell. So if we try to launch a container that has an entrypoint setup with something incompatbile, it will just fail anyway, and you then still need to override it.

**Comment by tvaughan** [comment]
> I'll make it optional for service boxes

What will be optional? I have services, for example https://github.com/tvaughan/docker-elasticsearch, that I would like to test on wercker. Will this be possible?

> but for the main box we need to be able to launch a shell. So if we try to launch a container that has an entrypoint setup with something incompatbile, it will just fail anyway, and you then still need to override it.

I don't quite understand this. For example, let's say I want to test https://github.com/tvaughan/docker-go on wercker. I could use a wercker.yml like:

    box: tvaughan/go:1.4.2
    build:
      steps:
        - script:
            code: |
             test -x /opt/go/bin/go && exit 0

How would I override the entrypoint? I hope I wouldn't have to create a different Docker container just for use on wercker. If this turns out to be the case, I'll have to duplicate all of my Docker containers.

**Comment by hatchan** [comment]
You're now able to override `entrypoints`. You can specify a `entrypoint` in the box or a service container. If a default entrypoint is defined in the container, then we will use that.

More info: http://devcenter.wercker.com/docs/containers/entrypoint.html
