### ISSUE TITLE
[Q] How to re-use a pipeline

### ISSUE THREAD

**Issue by kkamkou** [wercker/support#244]
Question: how could I re-use one shared pipeline? (I've checked closed and open tickets first)
For example, I have a plan:
```
A - B - D
  - C - D
  - E - F - G
```

`D` is `rsync`ing artifacts. I don't need many of them, just one. How can I do it? Or, what is the reason to avoid such a shared step?

**Comment by Hashfyre** [comment]
We have the same use case too, I implore the devs to come up with a constructive answer.

**Comment by flenter** [comment]
First of all: I can confirm that we do want to add this and it's part of a future update for workflows.

The main reason we don't support it now: is that workflows are defined (in the database) as links between pipelines (not as the graphs like we display them). Re-using pipelines in the current system creates problems such as infinite loops, determining the starting point etc.

In the mean time: please note that several pipelines in the web interface can point to the same yaml section (i.e. reuse steps etc), unfortunately this means env vars may need to be recreated and the pipeline needs to have a unique name in the web interface.
