### ISSUE TITLE
Revert workflows / Fix git statuschecks

### ISSUE THREAD

**Issue by Hashfyre** [wercker/support#260]
<Inadvertent move to Workflows -> Git Statuschecks failing>

Additional information: 

One of Our core Apps got inadvertently moved to workflows without external agency from our end, after which all `git statuschecks` have been stuck on `Expected: waiting for status to be reported`

Screenshot:
<img width="854" alt="screen shot 2016-09-20 at 4 39 49 pm" src="https://cloud.githubusercontent.com/assets/581287/18668055/e532b192-7f50-11e6-93ad-0a77dc31099d.png">

We need either a way to revert back our project from workflows to classic, or we need a fix for correcting the `git statuschecks`

This is really business critical for us and I hope wercker support can reach out and help us with this.

- wercker environment: app.wercker.com
- Docker environment: default workflows env

**Comment by captn3m0** [comment]
Why is the statuscheck proving hard to fix? API was already on the new docker system, so it shouldn't be that hard?

**Comment by Hashfyre** [comment]
It has come to our notice that wercker has stated this migration as an event, it'd still have been a much better experience if owners of each Application got informed about the move in place of the surprises that we had to handle.
