### ISSUE TITLE
Build status sync to GitHub's PRs and commits

### ISSUE THREAD

**Issue by turboMaCk** [wercker/support#263]
Hello!

Looks like there is some issue with synchronisation of build statuses back to Github since yesterday. Build status is not reported back to Github even I see payload in GH repo's web hooks.

We've ran into this on all our projects so this doesn't look like to be setting specific.

Is this a know issue? Is there any way how to resolve this issue or should we wait for some fix to be deployed?

- Fix webhooks does not fixed this
- Re-adding repository access doesn't fix this
- Removing webhook (GitHub) and adding it again doesn't fix this

Thanks,
Marek

Additional information:

- wercker environment: hosted
- OS: Linux in Wercker infrastructure

**Comment by hatchan** [comment]
You need to active "report to scm" on the workflow that you want to report the github status (can be more than 1).

**Comment by turboMaCk** [comment]
Thank you @hatchan. This was really hard to find in UI (I'm not much good in computers).
