### ISSUE TITLE
Build runs not showing via API

### ISSUE THREAD

**Issue by earnaway** [wercker/support#264]
If I call https://app.wercker.com/api/v3/applications/{org}/{app}/builds then I don't see my recent builds, last one (for me) was the 20th Sept and have had numerous builds since then.

It seems to coincide with the change over to Wercker Workflows, no builds since then are showing in the API.

Anyone else having this issue?

**Comment by hatchan** [comment]
We migrated to a new stack, you should now use the run endpoint: http://devcenter.wercker.com/api/endpoints/runs.html

**Comment by earnaway** [comment]
Excellent, just what I needed.
(the footer on Wercker UI page still points to old API docs, which is where my confusion came from)
