### ISSUE TITLE
Box [box-name] defined in wercker.yml not found

### ISSUE THREAD

**Issue by WarFox** [wercker/support#271]
Failed step: setup environment - Box nodesource/trusty defined in wercker.yml not found

- wercker environment: hosted

Additional information: 
My builds are failing with the above message, for any box type I try.

Failed step: setup environment - Box node defined in wercker.yml not found
Failed step: setup environment - Box node:6.7 defined in wercker.yml not found
Failed step: setup environment - Box nodesource/trusty defined in wercker.yml not found
Failed step: setup environment - Box nodesource/jesse:argon defined in wercker.yml not found
Failed step: setup environment - Box node:4.2.6-slim defined in wercker.yml not found
Failed step: setup environment - Box python:2.7-slim defined in wercker.yml not found
Failed step: setup environment - Box node:4.2.6-slim defined in wercker.yml not found

This is the application link: https://app.wercker.com/applications/54f21affb05d633123008a6e

I can't figure out why this is happening. Please help me figure out.

**Comment by hatchan** [comment]
You are trying to use Docker images on our legacy stack. This stack does not support Docker. You need to delete the application and create it again, after which it will be the new stack and you can use Docker images.

**Comment by WarFox** [comment]
I see, thanks for the info.
I got it working with the legacy box
```
box: wercker/ubuntu12.04-nodejs0.10
```

Thanks much. Closing this issue.
