### ISSUE TITLE
Setup Environment step show an error

### ISSUE THREAD

**Issue by karlkori** [wercker/support#273]
My builds stop working, during Setup Environment step I got an error:
Get https://codeload.github.com/wercker/wercker-init/tar.gz/v1.0.0: dial tcp: lookup codeload.github.com on 11.1.2.10:53: read udp 10.2.50.2:37854->11.1.2.10:53: i/o timeout

**Comment by karlkori** [comment]
looks like it was temporary problem - now it works

**Comment by hatchan** [comment]
It appears GitHub is having some issues, so might occur again.
