### ISSUE TITLE
Run fails on setup environment 

### ISSUE THREAD

**Issue by musto101** [wercker/support#281]
The pipeline runs fine on the CLI but breaks when pushed to remote host. The only error message is:

Command exited with exit code: 1

Additional information:

- wercker environment: <hosted>
- OS: <windows>
- Docker environment: <custom>
- Docker machine driver used: <virtualbox>

**Comment by musto101** [comment]
Hello?

Are you guys serious? It's been three days and no response to this. Your documentation is out of date and your service is buggy. You should be jumping at the chance to fix these issues. It shouldn't be the case that I have to contact you on twitter to get a response.

**Comment by riceo** [comment]
Hey @musto101,

Thanks for your patience, and sorry for the frustration. I'll take a look in to your application now, if you could kindly:

1. Provide the application name
2. Enable support on the application (Application -> Options Tab -> Set support to "yes")

If you're in the [public slack community](werckerpublic.slack.com) we can chat in realtime (@riceo)

Thanks

**Comment by musto101** [comment]
Hi @riceo 

The application name is Iris. I have enabled support. 

I look forward to hearing from you
Thanks

**Comment by riceo** [comment]
Thanks! Could you please dump the output of `docker version` and `docker info` locally please? It's interesting that this is working with the Wercker CLI but not on Web.

**Comment by musto101** [comment]
--> No Docker host specified, checking: /var/run/docker.sock                          │
--> Executing pipeline                                                                │
--> Running step: setup environment                                                   │
Pulling from musto101/wercker_testing: latest                                         │
Digest: sha256:48655625d7f0e0481a651ad55a94d258071f5d6a8b8462b5a9fb907f94c1301f       │
Status: Image is up to date for musto101/wercker_testing:latest                       │
--> Copying source to container                                                       │
--> Running step: wercker-init                                                        │
--> Steps passed: 4.37s                                                               │
--> Pipeline finished: 5.37s

**Comment by musto101** [comment]
I don't have access to the wercker public slack. Perhaps it would be easier if you send me an invite to access the slack channel.

Thanks

**Comment by riceo** [comment]
Oops I sent the wrong link, please use this for Public Slack: http://slack.wercker.com/

Thanks for the Wercker CLI output, but it's the output of running the commands `docker version`  and `docker info` from your machine we need.

Cheers

**Comment by musto101** [comment]
Apologies
docker version:
[lonhm@ip-10-85-4-12 iris]$ docker version                                            │
Client:                                                                               │
 Version:      1.12.2                                                                 │
 API version:  1.24                                                                   │
 Go version:   go1.6.3                                                                │
 Git commit:   bb80604                                                                │
 Built:                                                                               │
 OS/Arch:      linux/amd64                                                            │
                                                                                      │
Server:                                                                               │
 Version:      1.12.2                                                                 │
 API version:  1.24                                                                   │
 Go version:   go1.6.3                                                                │
 Git commit:   bb80604                                                                │
 Built:                                                                               │
 OS/Arch:      linux/amd64  

docker info:

 Pool Name: docker-202:1-1557984-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.25 GB
 Data Space Total: 107.4 GB
 Data Space Available: 34.03 GB
 Metadata Space Used: 16.66 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 6.897 GiB
Name: ip-10-85-4-12.eu-west-1.compute.internal
ID: DIIV:MS5L:CPUR:YDAM:RLR2:LMBU:K3MD:E4VJ:XUUE:KOG5:I5NX:EIKK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: musto101
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Comment by riceo** [comment]
Just to documentation's sake - The issue was resolved on the public slack channel. It turned out to be caused by adding environment variables with dollar signs in the name on Wercker. 

We have opened an issue on our internal Web repo for adding some validation warnings on the environment variable name input.
