### ISSUE TITLE
"Classic" Workflow Deploy Target Environment Variables Not Reflected

### ISSUE THREAD

**Issue by brettcrowell** [wercker/support#284]
Good evening,

It seems that changes made to my Deploy Target / Environment Variables in a "classic" workflow are no longer reflected in Node's `process.env`.  Values shown in the "environment variables" Build Step are also incorrect.

For context, I'm referring to the variables configured under "Deploy pipeline" at the following route...

```
https://app.wercker.com/applications/:application_id/settings/targets/target_id
```

Is this a known issue in the "classic" workflow?

Separately, it seems my app is stuck in the "classic" stack, is it currently possible to migrate it manually (perhaps allowing me to avoid the issue above entirely)?

Thanks,

Additional information:

- wercker environment: hosted
- OS: (mac)
- Box: wercker/nodejs

**Comment by akupila** [comment]
Thanks for reporting this. We've discovered a problem that could cause this to happen. We just deployed a fix, could you try again?

**Comment by brettcrowell** [comment]
Seems to have been fixed, many thanks for the prompt support!

**Comment by akupila** [comment]
Good to hear!
