### ISSUE TITLE
Please kill stuck deploy

### ISSUE THREAD

**Issue by mkj-pendo** [wercker/support#285]
I have a deploy job that's been stuck for hours: 5829eebf3599de0100bc8636

I restarted deploy successfully with another job, so please kill the stuck job so that it doesn't come back as a zombie later and break us.

Thanks much!

**Comment by riceo** [comment]
Usually in cases where the job is stuck in the waiting state for long periods of time there is no real job attached to what the front-end reports. I have marked this run as "aborted" for you. Thanks for reporting!

**Comment by mkj-pendo** [comment]
Thanks! Is there a way to abort from the UI that I missed?
