### ISSUE TITLE
Unable to use Wercker in Firefox

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#287]
Trying to login and do things in my Wercker account, but am unable to do anything on Firefox. Works fine with Safari. Screenshot of the buggy behavior in Firefox shown below. Also beyond that version info is included.

<img width="1554" alt="screen shot 2016-11-16 at 2 46 56" src="https://cloud.githubusercontent.com/assets/3019665/20338767/046334a6-aba7-11e6-9f59-09fc4519f940.png">

Additional information:

- wercker environment: hosted
- OS: Mac 10.9.5
- Firefox: 49.0.2 and 50.0
- Safari: 9.1.3

**Comment by flenter** [comment]
@jakirkham I'm unable to reproduce it on osx (though version 10.12.1) & firefox 50 (with and without adblock plus). 

Are there any javascript errors? If you go to tools -> web developer -> web console there shouldn't be any errors.

Or maybe it's related to extensions, what other extensions do you have installed? Was I right that it's adblock plus you have installed?

**Comment by jakirkham** [comment]
I don't know how things got so messed up, but I'm not seeing the issue this morning. Going to close for now. Will reopen and investigate further if it reoccurs.
