### ISSUE TITLE
Step failing on apt-get (because source are using HTTPS?)

### ISSUE THREAD

**Issue by smadbe** [wercker/support#288]
Since this morning, we have a step which fails (even on builds which were ok before). It fails at `apt-get update`. The error is `W: Failed to fetch https://deb.nodesource.com/node_0.12/dists/trusty/main/source/Sources  gnutls_handshake() failed: Handshake failed`.
The APT source mentioned is ok, apparently it is because it is using HTTPS. 
Have you changed something regarding caching APT HTTP recently ? 

Additional information:

- wercker environment: hosted
- Docker machine driver used: phusion/passenger-ruby22:0.9.18

**Comment by termie** [comment]
hi there, any chance you could try running the build (or at least this step) locally using the wercker cli? https://www.wercker.com/wercker-cli we aren't experiencing this but the cert seems valid on the nodesource.com site

**Comment by smadbe** [comment]
Now this is working. Thx.
