### ISSUE TITLE
Clarification regarding custom Docker containers

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#29]
Is there some base image that exists before our container is pull down? If so, what does it include?

**Comment by hatchan** [comment]
If you are referring to our new stack, than no we do not extend the image with some extra base layers. 

We do inject a small sh script which contains a few functions, see: https://github.com/wercker/wercker-init/

**Comment by jakirkham** [comment]
Thanks for clarifying @hatchan. Two related follow up questions.

1. How are the docker images started? Is it something like `docker run -it <image> /bin/bash`?
2. How does this shell script get inserted?

Sorry to barrage you with questions. I'm having failures instantly after my docker image is downloaded and am trying to understand what is causing this.
