### ISSUE TITLE
Hosted wercker job stucks

### ISSUE THREAD

**Issue by shellka** [wercker/support#298]
Owner\Application: shellka/wt-server2
Build: #8f54897

I cannot cancel it also.

**Comment by shellka** [comment]
Almost the same as: https://github.com/wercker/support/issues/238

**Comment by shellka** [comment]
Old commits are correct can be re-deployed, but new builds are stuck

**Comment by neilcampbell** [comment]
I'm having the same issue

**Comment by maryo** [comment]
I am also having the same issue

**Comment by riceo** [comment]
We were having a few issues with some builds last night. Anything that is listed as waiting for several hours won't run. You should be able to mark them as aborted by going to the "list" view on the runs tab (right side of the page, change from the group view to list view), then select abort on the stuck runs.

Runs should re-start successfully now. Thanks for reporting this and bearing with us. Please ping if any further runs get stuck.

**Comment by shellka** [comment]
When i click on 'cancel' button i have message that "Workflow aborder succesfully" but nothing happend with queue

**Comment by riceo** [comment]
@shellka Is that on group view or list view? 

![List view](https://d3vv6lp55qjaqc.cloudfront.net/items/1z3U2a2R3M3d0d3v3v2C/%5Be59caea44db1e5928e55b0b7a64dbe64%5D_Image%25202017-01-10%2520at%252010.09.57%2520am.png?X-CloudApp-Visitor-Id=229620&v=ad9bc8b1)

**Comment by maryo** [comment]
@riceo Aborting from inside the List view aborted it succesfully. But new commit is still "waiting to start" (for about 15 minutes now)

**Comment by shellka** [comment]
On groupped, just switched to list view... yes there i can cancel it.

**Comment by shellka** [comment]
Yes, i have the same issue - new build stuck again

**Comment by neilcampbell** [comment]
@riceo Still saying "waiting to start" after cancelling old build and triggering new ones

**Comment by riceo** [comment]
@maryo @shellka @neilcampbell could you please enable support on your applications and either link them here or open a support ticket on Wercker Web (question mark icon on the bottom right side of any page). I'll take a closer look. Thanks.

**Comment by neilcampbell** [comment]
@riceo Just created a support ticket and enabled support on my account

**Comment by riceo** [comment]
Thanks @neilcampbell. Investigating.

**Comment by shellka** [comment]
Sure, i already contacted support in this morning, but i just have enabled support and contacted again.

**Comment by shellka** [comment]
Oh, i just have tryed new commit\build and looks like build passed, but deploy doesn't start.

**Comment by shellka** [comment]
Thanks you, now it works =)

**Comment by riceo** [comment]
Glad to hear it! Anyone else still having problems?

**Comment by maryo** [comment]
Great. Our build also works now. Thanks
