### ISSUE TITLE
ewok: cli not supporting services propely

### ISSUE THREAD

**Issue by qraynaud** [wercker/support#31]
I have the following in my wercker.yml:

```yaml
build:
  services:
  - dramalho/elasticsearch:0.0.1
```

When I try `wercker build` I get the following error:

```
ERROR Error during check access
ERROR --> Step failed: setup environment
GET https://registry.hub.docker.com/v1/repositories/mongodb/images returned 404
ERROR GET https://registry.hub.docker.com/v1/repositories/mongodb/images returned 404
```

I picked up the lines on https://app.wercker.com/#applications/54763630a60c33c27c3d252f/tab/details though I replaced the `@` by `:` (I suppose the registry webpage is wrong on this)

**Comment by mies** [comment]
Hi is your elasticsearch service present on Dockerhub or on the wercker registry? Wercker registry boxes are not supported on our Ewok stack:http://devcenter.wercker.com/docs/pipelines/stacks.html

**Comment by qraynaud** [comment]
Ah ok. I had missed that part. Sorry about that.
