### ISSUE TITLE
Running a build using a private Docker image from Quay.io fails with 403

### ISSUE THREAD

**Issue by timflapper** [wercker/support#34]
Since last night all our builds are failing with the error: `GET https://quay.io/v1/repositories/springest/one/images returned 403`
![](http://img.springe.st/2015_06_04_11_02_50_s1mlt.png)

The same issue happens when running `wercker build` locally:
![](http://img.springe.st/2015_06_04_11_13_31_z2nqr.png)

Running the same command, with the same user credentials using boot2docker locally works just fine. I hope you can find a quick solution because it makes our Wercker environment completely unusable right now.

**Comment by hatchan** [comment]
Thanks for the report. Which wercker version are you using?

**Comment by timflapper** [comment]
@hatchan, Locally i'm running `wercker version 1.0.113 (Compiled at: 2015-04-24T15:36:51Z, Git commit: 53d18796c7137c908c956cb0b06d1896a0030e50)` but as you can see in the screenshot it seems to happen in your latest version (1.0.153) as well.

**Comment by hatchan** [comment]
Has the `wercker build` locally always worked? 

- If using a env var or `--environement`, prefix the env var with `X_`. (so `export X_QUAY_USERNAME='....'`
- If that didn't work, could you try hardcoding the username + password in the wercker.yml 

The hosted version might have a different issue, which I'm investigating now

**Comment by timflapper** [comment]
You're right. Locally I forgot to add `--environment`. Running `wercker build` locally does indeed work. I also updated to the latest version `wercker version 1.0.152 (Compiled at: 2015-06-02T10:54:01Z, Git commit: f98fade43d1fee1f9fe5225fb82688216ce89836)`.

**Comment by hatchan** [comment]
I've just indentified the issue. Will let you know when I've deployed the fix.

**Comment by timflapper** [comment]
@hatchan, great to hear. Thank you!

**Comment by hatchan** [comment]
We've just deployed the fix. Can you confirm that it is working again?

**Comment by timflapper** [comment]
@hatchan, yep. It's fixed. Thank you.

**Comment by hatchan** [comment]
Good to hear, sorry for the inconveniences.

**Comment by joepjoosten** [comment]
I've got version 1.0.152, but i've the same problem with the local build:

Runing:
`wercker --environment wercker.env build`

wercker.env file has:
```
QUAY_USER=xxxx
QUAY_PASS=xxxx
```

and wercker.yml:
```
build:
  box:
    id: quay.io/xxx/xxx
    username: $QUAY_USER
    password: $QUAY_PASS
    tag: xxx-xxx
    registry: quay.io
```

In which version is the fix? And can i download this version?

**Comment by hatchan** [comment]
@joepjoosten The `wercker.env` files requires that you add the `X_` prefix. This prefix will be stripped by wercker and be made available during a build.

So `X_QUAY_USER` in the `wercker.env` file will become `QUAY_USER` during a build
