### ISSUE TITLE
Cannot fetch private image from docker hub

### ISSUE THREAD

**Issue by tal-moshayov** [wercker/support#35]
something got broken in the last 2 days and I cannot fetch a private docker image any more even though the username/password are correct. 
I get "GET https://registry.hub.docker.com/v1/repositories/<docker-user>/<image-name>/images returned 404"

**Comment by hatchan** [comment]
We've just deployed the fix. Can you confirm that it is working again?

**Comment by tal-moshayov** [comment]
yes it is. thanks for the quick turnaround!
