### ISSUE TITLE
Bad status code fetching tarball: https://api.github.com/repos/wercker/wercker-init/tarball

### ISSUE THREAD

**Issue by tal-moshayov** [wercker/support#36]
I've started getting the following error at the setup environment phase:
`Bad status code fetching tarball: https://api.github.com/repos/wercker/wercker-init/tarball`

What does it mean and how do I fix?

Here's my [wercker.yml](https://bitbucket.org/snippets/silo_co/7yy5R)

**Comment by hatchan** [comment]
This is a problem on our side. We're working on fixing it.

**Comment by tal-moshayov** [comment]
I see it's fixed now. thx.

**Comment by hatchan** [comment]
Yes was just about to post. Again sorry for the inconvenience.

**Comment by tal-moshayov** [comment]
Hello, this issue has just resurfaced. My deploys are getting rejected with 
```wercker-api: resource not found (status code: 404)```

**Comment by captn3m0** [comment]
Facing the same issue.

**Comment by hatchan** [comment]
Could you update to the latest version of the wercker cli? IF the problem still persist, please open a new issue
