### ISSUE TITLE
error parsing wercker.yml (mapping values are not allowed in this context)

### ISSUE THREAD

**Issue by tal-moshayov** [wercker/support#42]
this [wercker.yml](https://gist.github.com/tal-moshayov/4e4402ffafcb982d0dc5) fails to build with the following error:
`Error parsing your wercker.yml: yaml: line 44: mapping values are not allowed in this context`

when I take out the `name:` line it works nicely. I guess there's a bug parsing that line.

**Comment by Tonnu** [comment]
Hi Tal, 

It looks like you're not indenting correctly. Your `name` and `code` section should be indented further. See also [this gist](https://gist.github.com/Tonnu/3cd2495a1361bbea0677).

**Comment by tal-moshayov** [comment]
correct. this fixed it. i wonder why it only fails there, as it works perfectly with that indentation at build time. anyway. thx!
