### ISSUE TITLE
No slack notification if build fails if script running over build time 

### ISSUE THREAD

**Issue by lukeaus** [wercker/support#43]
I got this message on a build twice in the last 48 hours:
Your script is taking too long: 25 minutes. Please update and run again.

However I did not receive notification in slack

I am using this in wrecker.yml:

  after-steps:
      - tsechov/ultimate-slack-notify@1.0.3:

**Comment by flenter** [comment]
Are you using the classic wercker environment or the new docker enabled one?

**Comment by hatchan** [comment]
When a build/deploy hits a timeout, no aftersteps will be run. This is expected behavior.
