### ISSUE TITLE
Disk space issues

### ISSUE THREAD

**Issue by timflapper** [wercker/support#44]
A lot of our builds are failing because of disk space issues:

```
Pulling repository postgres
Pulling image (9.3.5) from postgres: 7032d58ddbf2
Pulling image (9.3.5) from postgres, endpoint: https://registry-1.docker.io/v1/: 7032d58ddbf2
Pulling dependent layers: 7032d58ddbf2

....

Status: Image is up to date for postgres:9.3.5
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
initdb: could not create directory "/var/lib/postgresql/data/global": No space left on device
initdb: removing contents of data directory "/var/lib/postgresql/data"
```

It doesn't seem to happen most of the time but once in a while a build seems to go through without a problem.

**Comment by flenter** [comment]
We're looking into it

**Comment by flenter** [comment]
Sorry for the late update, but we've resolved the disk space issues a few hours ago

**Comment by djfpaagman** [comment]
Still happening as of 13 minutes ago. @fienter @timflapper 

Not sure if you can access the build, but [here is the link](https://app.wercker.com/#buildstep/55793cbdbc00eeab44164b2d).

**Comment by flenter** [comment]
Support is not

**Comment by mies** [comment]
@djfpaagman @timflapper we're looking into this!

**Comment by mies** [comment]
@djfpaagman @timflapper also, could add support for us?

**Comment by djfpaagman** [comment]
@mies done!

**Comment by miriamtocino** [comment]
One of my builds also have the same problem @mies. Here is the [link](https://app.wercker.com/#buildstep/55783ae5321aab414700dd50) to mine.

**Comment by mies** [comment]
@djfpaagman @timflapper @miriamtocino jobs should be picked up again. The issue that we're running into is that docker is doing a poor job of cleaning up after itself. We're looking into being more aggressive about that. Sorry for the trouble!
