### ISSUE TITLE
Permission denied on Ewok

### ISSUE THREAD

**Issue by ertrzyiks** [wercker/support#49]
Hey,

on application ertrzyiks/ertrzyiks-pl im using push to deploy strategy and with exactly the same configuration of wercker and remote server deploy succeed with Classic infrastructure and fails on Ewok.

Im using key pair variable and `add-ssh-key` step to manage keys.

Build on Ewok: https://app.wercker.com/#deploystep/557d51f9f0c2c2a14408b28d
Build on Classic: https://app.wercker.com/#deploy/557d52f3f0c2c2a14408b39a

I got permission denied and with verbosed ssh command i saw it expected passphrase for key without passphrase. I probably dont have enough knowledge on architecture to find proper solution, after hours on debugging im happy it works on Classic setup.

**Comment by hatchan** [comment]
We're looking into some possible issues due to incorrect escaping of environment variables.

**Comment by hatchan** [comment]
We've released a fix for the problem. Please reopen, if it the problem still persist.

**Comment by ertrzyiks** [comment]
It works, thanks!
