### ISSUE TITLE
DOC: Regarding using docker with a pulled image (note tag)

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#52]
Maybe this was clearly stated and I simply missed it, in which cases apologies and please disregard.

Otherwise, it would be really helpful to not that an image pulled down with the CLI will have a tag other than `latest` (e.g. `test`). If the naming scheme is more complicated than just `test` every time, it would be nice to know what that naming scheme is. All of this should be documented ideally right after explaining how to get the image via the wercker CLI.

**Comment by flenter** [comment]
Can you explain a bit more what you mean by this? Are you referring to the containers you can pull via the `wercker pull` command? 

Does this page describe what you want to know: http://devcenter.wercker.com/docs/using-the-cli/pulling-containers.html

**Comment by jakirkham** [comment]
Yes, I think this helps. When I was using this previously, there were other tags being used for the Docker images. Could I suggest the tag `latest` be used? This would avoid the end user needing to know anything about the tag at all.
