### ISSUE TITLE
Pushing commits to a github branch for a PR creates two builds

### ISSUE THREAD

**Issue by christophercurrie** [wercker/support#58]
When pushing commits to a branch in github, wercker will create a build for that branch. If a PR is created from that branch, and a commit is added to it, now wercker will create two builds for the same commit, one for the branch, and one with a name like 'Merge for pull request <pr#> "<pr name>"'. Since we only get two builds at a time, this one commit now blocks any other project from being built.

**Comment by hatchan** [comment]
Atm, this is expected behavior. 

If a repository is forked, then we do new builds for incoming PR's. However we also do builds for internal PR's. 

We are looking at doing the "merge for pull requests" only for external PR's.

**Comment by christophercurrie** [comment]
Thanks, that feature would definitely help.

**Comment by hatchan** [comment]
We're now only doing the "merge for pull requests" for pull request that are coming from external repositories.
