### ISSUE TITLE
wercker/android environment results in GET https://registry.hub.docker.com/v1/repositories/wercker/android/images returned 404 error

### ISSUE THREAD

**Issue by tribbloid** [wercker/support#65]
This is my wercker.yml file:

		box: wercker/android

		build:
		  steps:
		    - script:
		        name: show base information
		        code: |
		          mvn -v
		    - script:
		        name: install sap jdbc jar into local maven repo
		        code: |
		          ./prepare-jar.sh
		    - script:
		        name: mvn clean install
		        code: |
		          ./test-install.sh

The build failed when reading the first line.

**Comment by hatchan** [comment]
The box specified in the wercker.yml is an old legacy box. You need to get an Docker container: http://devcenter.wercker.com/docs/faq/migration-tips-v2.html#how-do-i-get-started-with-the-docker-stack-and-containers-
