### ISSUE TITLE
All builds queued, none running

### ISSUE THREAD

**Issue by timflapper** [wercker/support#66]
Currently we have 2 builds and 1 deploy queued and none running. Is there an issue with capacity that might make it take longer for queued builds to be picked up?

**Comment by flenter** [comment]
We're currently upgrading the docker-enabled infrastructure: http://blog.wercker.com/2015/07/01/Infrastructure-Upgrades.html

**Comment by timflapper** [comment]
@flenter, thank you. Did not get that message :)

**Comment by janakg** [comment]
all builds are queued for a few hours. is there any solution for this?
