### ISSUE TITLE
ENH: Provide setting to make image storage optional

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#69]
It would be nice if there was a setting (ideally in the web app) that allowed for enabling/disabling storage.

This could provide a reasonable workaround for issues like this ( https://github.com/wercker/support/issues/62 ).

**Comment by Tonnu** [comment]
This is something that we're aware of and is on the todo list. I can't give you any ETA of when we might add this however.

**Comment by jakirkham** [comment]
Another thought is to be able to retry the storage step independently from running the tests.

**Comment by hatchan** [comment]
The store step should not fail anymore, see #62
