### ISSUE TITLE
internal/docker-push to IBM Containers/ Bluemix

### ISSUE THREAD

**Issue by lukeadams** [wercker/support#70]
Currently Bluemix requires the IBM cf/ice command line installed alongside docker to configure the auth token, which can't be used in ewok because the build environment is inside a container. 
I'm currently investigating if I can extract the token and pass it in like GCE does. Just waiting for my Windows VM to finish updating...

**Comment by mies** [comment]
Cool keep us posted! Would love to get this working and see if we can do/feature a blogpost on how to build & deploy with wercker to IBM BlueMix, if that's something that interests you?

**Comment by lukeadams** [comment]
Yay! The ICE cli is written in python, so I'm digging into it.

**Comment by lukeadams** [comment]
Also: if you extract your bearer token from the CLI it works :)
![YESSS](http://cl.ly/image/1c3Q0V0X1m1P/Image%202015-07-09%20at%205.23.20%20PM.png)

**Comment by lukeadams** [comment]
There are two ways:
- Sign in and get token every deploy (requires placing Bluemix Username and Password into env variables)
- Extract the token from your local machine [PREFERRED]

**Comment by lukeadams** [comment]
The first way:
- Install jq and the cf CLI (apparently ice CLI just proxies calls to cf ...)
- login with cf
- use jq to extract the token

Uses Linux64 binaries. Set `$IBM_EMAIL` to your Bluemix email address and `$IBM_PASSWORD` to your Bluemix password
```yml
deploy:
  - steps
    - script:
      name: Initialize jq and cf
      code: |
        cd /
        wget -O cf.tgz https://cli.run.pivotal.io/stable?release=linux64-binary&source=github && tar -xvf cf.tgz && rm cf.tgz
        wget -O jq http://stedolan.github.io/jq/download/linux64/jq
        chmod +x cf jq
        cf login -a https://api.ng.bluemix.net -u $IBM_EMAIL -p $IBM_PASSWORD
        BASETOKEN=$(jq -r '.AccessToken' config.json | cut -d ' ' -f 2)
        SPACE=$(jq -r '.OrganizationFields.Guid' config.json)
        TOKEN="$BASETOKEN|$SPACE"
    - internal/docker-push:
      username: bearer
      password: $TOKEN
      <other stuff>
```

**Comment by lukeadams** [comment]
The second way <typing right now>
