### ISSUE TITLE
/pipeline/output is empty in deploy step

### ISSUE THREAD

**Issue by adamreeve** [wercker/support#71]
I'm probably just misunderstanding how this is supposed to work.

I have a build step that compiles my application and copies the build output into `$WERCKER_OUTPUT_DIR`.

Then in my deploy step I use the `internal/docker-push` step to push a docker image to the public docker hub.

But when I pull down that image from the hub and try to use it, /pipeline/output is empty. So I'm a bit lost as to how I'm supposed to get my build output into the docker image?

**Comment by mies** [comment]
For using `internal/docker-push` the correct folder where the binary would show up is: `/pipeline/source`

Feel free to have a peek at my `wercker.yml` file:
https://github.com/mies/wercker-push-quay/blob/master/wercker.yml

**Comment by adamreeve** [comment]
Hmm `/pipeline/source` seems to just contain my source code without any of the compiled binaries.

**Comment by adamreeve** [comment]
Oh nevermind, it works on the actual wercker service, but seems to have the wrong contents when I try the deploy steps locally (matches my source dir instead of the result of a previous build). Thanks! Makes sense that the output dir of the build step is the source dir for the deploy step...

**Comment by marshall007** [comment]
`$WERCKER_OUTPUT_DIR` changing behavior in the deploy pipeline is not well documented. Since this change in behavior is not reflected when running pipelines locally, it makes it even more difficult to track down.

I think this should be re-opened until the docs are updated and/or the local builds reflect reality.

**Comment by adamreeve** [comment]
I created a new issue instead of reopening this one, thought that would be a bit clearer.

**Comment by marshall007** [comment]
@adamreeve thanks!

**Comment by metral** [comment]
`$WERCKER_OUTPUT_DIR` not being specified as `/pipeline/source` for `internal/docker-push` threw me for a loop for a bit. I thought it would be identical to the `internal/docker-scratch-push` where "it injects the files present in the $WERCKER_ROOT environment variable into the root of the container."

Perhaps that should be specified in the docs for `internal/docker-push` ?

**Comment by metral** [comment]
Took it on myself to create the doc PR (https://github.com/wercker/docs/pull/314) about clearing up where $WERCKER_ROOT in internal/docker-push is located
