### ISSUE TITLE
Deploy fails on get code step

### ISSUE THREAD

**Issue by ertrzyiks** [wercker/support#77]
From today morning i cant deploy any of my applications using Ewok architecture. It fails on Get code step, see: https://www.dropbox.com/s/ma2vpqso2lou7hy/Screenshot%202015-07-23%2012.16.59.png?dl=0

Everything is fine on classic architecture.

I tested deploy on 3 application so i think its global. 
I have support enabled here: https://app.wercker.com/#deploystep/55b0bde1f32b86a9291bd760

**Comment by hatchan** [comment]
We are aware of the issue, and are close to fixing it. Sorry for the inconvenience.

**Comment by ertrzyiks** [comment]
It works! Thanks
