### ISSUE TITLE
[feature] Change the URL of a repository

### ISSUE THREAD

**Issue by kkamkou** [wercker/support#78]
This issue copy-pasted from the `uservoice`.

**Comment by Tonnu** [comment]
Hi, thanks for suggesting this. It's currently included in our roadmap but we don't have a high priority assigned to it. Depending on how much interest is shown in this feature, we might change that though.

**Comment by pimterry** [comment]
I would use this! In fact, I need to use this now. Is there anything I can do about that, or do I have to create a new job from scratch?

**Comment by kkamkou** [comment]
any progress for 1 year?
