### ISSUE TITLE
tests timing out at 25 minutes

### ISSUE THREAD

**Issue by alexfarrill** [wercker/support#83]
Our tests are taking about 2-3 times as long to run since migrating to the docker stack and timing out after 25 minutes.  Any thoughts on why it would be taking longer to run or if the 25 minute limit can be raised?

**Comment by hatchan** [comment]
Not sure what is causing the slow. You can however change the timeouts using your wercker.yml: http://devcenter.wercker.com/docs/faq/how-to-bypass-timeouts.html

**Comment by metral** [comment]
i too am experiencing extra slower build times with local wercker on a docker stack vs native testing on the host itself...difference of an extra 2 min or so on wercker stack for what is a sub-10second test suite
