### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by kkamkou** [wercker/support#86]
on: https://app.wercker.com/#applications/52ef31ea2f3e91f33d01cb05/tab/details
Reason: https://app.wercker.com/api/v2/steps/satotka/STEP-EBS-deploy/0.0.4/readme
`Content-Length: 0`

I can't see the Read-me section.

**Comment by hatchan** [comment]
Looks like this issue has been resolved, the readme was empty
