### ISSUE TITLE
3 queued builds, no builds running

### ISSUE THREAD

**Issue by timflapper** [wercker/support#91]
It seems like our builds aren't getting started anymore. Currently we have 3 queued builds and nothing running.

**Comment by flenter** [comment]
Looking into it

**Comment by timflapper** [comment]
Thank you!

**Comment by flenter** [comment]
The problem seemed to be caused by issues with amazon's S3 infrastructure:

http://status.aws.amazon.com/ or the rss feed: http://status.aws.amazon.com/rss/s3-us-standard.rss

**Comment by flenter** [comment]
Seems like the problems with S3 have mostly been resolved.

**Comment by timflapper** [comment]
Yep, it looks like jobs are slowly getting started again. Thank you for your quick response.
