### ISSUE TITLE
Intermittent Ewok builds not starting

### ISSUE THREAD

**Issue by timflapper** [wercker/support#94]
After yesterday's issues where no builds would start because of S3 problems we are still seeing intermittent builds not starting while builds that are queued later actually do start. Is this still an issue related to yesterday's S3 problems?

**Comment by timflapper** [comment]
Update on the previous comment: After aborting and restarting the build several times it sometimes does start.

**Comment by flenter** [comment]
I'll look into it. Can you send us links to builds that didn't work for you?  Preferable via uservoice (the question-mark button on app.wercker.com). That would really help.

**Comment by timflapper** [comment]
@flenter, I sent you the link to the build that won't start.

**Comment by flenter** [comment]
awesome, thanks!

**Comment by timflapper** [comment]
Seems to be working again.
