### ISSUE TITLE
Landing page language toggle buttons are broken

### ISSUE THREAD

**Issue by jadengore** [wercker/support#99]
![](http://f.cl.ly/items/281x0z1O2E190L07210u/Image%202015-08-11%20at%2011.27.22%20AM.png)

The language toggles on the language page are broken, and will not toggle anything besides Go. I'm getting this error in the console:

`Uncaught TypeError: Cannot read property 'addEvent' of undefined at metrics.js:4`

Currently using Chrome 44 on OS X.

**Comment by birkholz** [comment]
I'm also having this issue. Chrome beta 45 on OS X.

**Comment by lindseybateman** [comment]
Thanks for reporting, could it be you guys are using something to block metrics?

**Comment by jadengore** [comment]
@lindseybateman I'm using uBlock Origin, I just toggled it off and it seems to be working now. So this toggle depends on metrics?

**Comment by lindseybateman** [comment]
Thanks! It shouldn't depend on it, we will fix this.

**Comment by lindseybateman** [comment]
We deployed a fix so it should be working when using some sort of blocker

**Comment by jadengore** [comment]
Thank you! I'll close this.
